"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { useJournalTools } from "@/lib/use-journal-tools";
import { AccountAnalytics, CapitalCard, Connections, OwnerAccess, RealHistory, journalApi, usePortfolioCapital, useServerJournal } from "@/components/journal-server";
import { ArrowUpRight, CalendarDays, ChartNoAxesCombined, ChevronLeft, ChevronRight, Download, Layers3, Link2, Wallet, X, Info, ArrowRight } from "lucide-react";
import { Dialog, DialogContent, DialogTitle, DialogDescription, DialogClose } from "@/components/ui/dialog";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from "@/components/ui/table";
import { makeDemo, sum, group, dateKey, money, percentOfCapital, type Trade } from "@/lib/journal";
const exchanges=["Binance","Bybit","OKX","Gate.io","Bitget","Aster","Hyperliquid","KuCoin","MEXC","Lighter"];
const months=["Январь","Февраль","Март","Апрель","Май","Июнь","Июль","Август","Сентябрь","Октябрь","Ноябрь","Декабрь"];
type Period={start:string;end:string;title:string};
const sign=(n:number)=>n>0?"positive":n<0?"negative":"neutral";
function Amount({value,unit,capitalUsd}:{value:number;unit:"usd"|"percent";capitalUsd:number}){const text=unit==="usd"?money(value):`${value>0?"+":value<0?"−":""}${Math.abs(percentOfCapital(value,capitalUsd)).toFixed(2)}%`;return <span className={sign(value)}>{text}</span>}
const exchangeIcons:Record<string,string>={Binance:"https://cdn.simpleicons.org/binance/F3BA2F",Bybit:"https://cdn.simpleicons.org/bybit/F7A83B",OKX:"https://cdn.simpleicons.org/okx/FFFFFF", "Gate.io":"https://cdn.simpleicons.org/gateio/3CC8C8",Bitget:"https://cdn.simpleicons.org/bitget/00D4C8",Aster:"https://www.asterdex.com/favicon.ico",Hyperliquid:"https://cdn.simpleicons.org/hyperliquid/9DE4D0"};
function ExchangeIcon({name}:{name:string}){return <span className={"exchange-icon ex-"+name.toLowerCase().replace(/\W/g,"")}><img src={exchangeIcons[name]} alt="" loading="lazy" onError={e=>{e.currentTarget.style.display="none"}}/><span className="exchange-fallback">{name.slice(0,2).toUpperCase()}</span></span>}
export default function Home(){
 const [authenticated,setAuthenticated]=useState(false);
 const onOpen=useCallback(()=>setAuthenticated(true),[]);
 return authenticated?<Journal onLogout={()=>setAuthenticated(false)}/>:<OwnerAccess onOpen={onOpen}/>;
}
function Journal({onLogout}:{onLogout:()=>void}){
 const [now,setNow]=useState(new Date(2026,8,16)),[month,setMonth]=useState(new Date(2026,8,1)),[exchange,setExchange]=useState("all"),[market,setMarket]=useState("all"),[mode,setMode]=useState("calendar"),[unit,setUnit]=useState<"usd"|"percent">("percent"),[period,setPeriod]=useState<Period|null>(null),[detailExchange,setDetailExchange]=useState("all"),[connectionOpen,setConnectionOpen]=useState(false),[installOpen,setInstallOpen]=useState(false),[demo,setDemo]=useState(false);
 const rangeStart=dateKey(new Date(month.getFullYear(),month.getMonth(),1));
 const rangeEnd=dateKey(new Date(month.getFullYear(),month.getMonth()+1,0));
 const server=useServerJournal(rangeStart,rangeEnd,!demo);
 const capital=usePortfolioCapital(!demo);
 useEffect(()=>{const actual=new Date(),d=new Date(actual.getUTCFullYear(),actual.getUTCMonth(),actual.getUTCDate());setNow(d);setMonth(new Date(d.getFullYear(),d.getMonth(),1));if("serviceWorker" in navigator)navigator.serviceWorker.register("/sw.js").catch(()=>{});},[]);
 const navigateDay=useCallback((date:string)=>{const [y,m,d]=date.split('-').map(Number);setMonth(new Date(y,m-1,1));setDetailExchange('all');setPeriod({start:date,end:date,title:new Date(y,m-1,d).toLocaleDateString('ru-RU',{day:'numeric',month:'long',year:'numeric'})});},[]);
 useJournalTools(navigateDay);
 const all=useMemo(()=>{if(!demo)return server.rows;const dates=[month,now,new Date(now.getFullYear(),now.getMonth()-1,1),new Date(now.getFullYear(),now.getMonth()+1,1)];return [...new Map(dates.flatMap(d=>makeDemo(d.getFullYear(),d.getMonth(),now)).map(t=>[t.id,t])).values()]},[month,now,demo,server.rows]);
 const filteredAll=useMemo(()=>all.filter(t=>(exchange==="all"||t.exchange===exchange)&&(market==="all"||t.market===market)),[all,exchange,market]);
 const rows=filteredAll.filter(t=>t.date.slice(0,7)===dateKey(month).slice(0,7));
 const first=dateKey(month),last=dateKey(new Date(month.getFullYear(),month.getMonth()+1,0)),today=dateKey(now),monthTitle=months[month.getMonth()]+" "+month.getFullYear(),days=new Date(month.getFullYear(),month.getMonth()+1,0).getDate(),offset=(month.getDay()+6)%7;
 const daily=Array.from({length:days},(_,i)=>({day:i+1,rows:rows.filter(t=>t.date===dateKey(new Date(month.getFullYear(),month.getMonth(),i+1)))}));
 const weeks=Array.from({length:Math.ceil((offset+days)/7)},(_,w)=>Array.from({length:7},(_,i)=>{const n=w*7+i-offset+1;return n>0&&n<=days?n:null}));
 const total=sum(rows),maxDaily=Math.max(1,...daily.map(d=>Math.abs(sum(d.rows))));
 const weekStart=new Date(now.getFullYear(),now.getMonth(),now.getDate()-(now.getDay()+6)%7),weekEnd=new Date(weekStart.getFullYear(),weekStart.getMonth(),weekStart.getDate()+6);
 const currentMonth=month.getMonth()===now.getMonth()&&month.getFullYear()===now.getFullYear();
 const selected=filteredAll.filter(t=>period&&t.date>=period.start&&t.date<=period.end),details=selected.filter(t=>detailExchange==="all"||t.exchange===detailExchange);
 function open(p:Period){setDetailExchange("all");setPeriod(p)}
 function openDay(n:number){const d=new Date(month.getFullYear(),month.getMonth(),n);open({start:dateKey(d),end:dateKey(d),title:d.toLocaleDateString("ru-RU",{day:"numeric",month:"long",year:"numeric"})})}
 function move(n:number){setMonth(new Date(month.getFullYear(),month.getMonth()+n,1))}
 const recordLabel=demo?"сделок":"записей PnL";
 const capitalUsd=demo?25000:Number(capital.data?.totalEquityUsd||0);
 const fmtPercent=(n:number,digits=2)=>`${n>0?"+":n<0?"−":""}${Math.abs(percentOfCapital(n,capitalUsd)).toFixed(digits)}%`;
 const fmt=(n:number)=>unit==="usd"?money(n):fmtPercent(n);
 function exportCsv(){const rs=period?details:rows;const str="\uFEFFdate,exchange,ticker,market,pnl_usd,fee_usd,funding_usd\n"+rs.map(t=>[t.date,t.exchange,t.ticker,t.market,(t.gross/100).toFixed(2),(t.fee/100).toFixed(2),(t.funding/100).toFixed(2)].join(",")).join("\n");const url=URL.createObjectURL(new Blob([str],{type:"text/csv;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download=`trading-journal-${period?.start||first}.csv`;a.click();URL.revokeObjectURL(url)}
 return <div className="app-shell"><header className="topbar"><div className="top-actions"><span className="private-label"><Wallet size={15}/>Личное пространство</span><button className="icon-button" onClick={()=>setInstallOpen(true)} aria-label="Установить приложение"><Download size={18}/></button><button className="secondary-button" onClick={async()=>{await journalApi("/logout",{});onLogout();}}>Выйти</button></div></header><main>
 <div className="page-heading"><div><div className="eyebrow">ВАША ТОРГОВЛЯ В ЦИФРАХ</div><h1>Торговый журнал</h1></div><div className="heading-actions">{!demo&&<CapitalCard data={capital.data} error={capital.error}/>}<button className="connect-button" onClick={()=>setConnectionOpen(true)}><Link2 size={17}/>Биржи<span className="count">{demo?"Демо":"API"}</span></button></div></div>
 <div className="demo-strip"><Info size={15}/><span>{demo?"Демо · пример торговой истории. Биржевые счета не подключены.":server.error||"Личные данные · синхронизация выполняется на сервере."}</span><button onClick={()=>{setDemo(!demo);setUnit("percent")}}>{demo?"Мои данные":"Показать демо"}<ArrowRight size={14}/></button></div>
 {!demo&&server.notice&&<p className="info-note">{server.notice}</p>}
 <section className="stats-grid" aria-label="Результаты по периодам">{[{label:"Результат за день",value:sum(filteredAll.filter(t=>t.date===today)),sub:now.toLocaleDateString("ru-RU",{day:"numeric",month:"long"}),p:{start:today,end:today,title:"Сегодня · "+now.toLocaleDateString("ru-RU")},icon:<ArrowUpRight size={19}/>},{label:"Результат за неделю",value:sum(filteredAll.filter(t=>t.date>=dateKey(weekStart)&&t.date<=dateKey(weekEnd))),sub:`${weekStart.getDate()}–${weekEnd.getDate()} · текущая неделя`,p:{start:dateKey(weekStart),end:dateKey(weekEnd),title:"Текущая неделя"},icon:<Layers3 size={19}/>},{label:"Результат за месяц",value:total,sub:monthTitle,p:{start:first,end:last,title:monthTitle},icon:<CalendarDays size={19}/>}].map((c,i)=><button key={c.label} className={"stat-card "+(i===2?"featured":"")} onClick={()=>open(c.p)}><div className="stat-top"><span>{c.label}</span>{c.icon}</div><strong className={sign(c.value)}>{fmt(c.value)}</strong><div className="stat-bottom"><span>{c.sub}</span><ArrowUpRight size={16}/></div></button>)}</section>
 <section className="workspace"><div className="workspace-toolbar"><Tabs value={mode} onValueChange={setMode}><TabsList className="view-tabs"><TabsTrigger value="calendar"><CalendarDays size={16}/>Календарь</TabsTrigger><TabsTrigger value="history"><ChartNoAxesCombined size={16}/>История</TabsTrigger></TabsList></Tabs><div className="filters"><Select value={exchange} onValueChange={setExchange}><SelectTrigger aria-label="Фильтр по бирже"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">Все биржи</SelectItem>{exchanges.map(e=><SelectItem key={e} value={e}>{e}</SelectItem>)}</SelectContent></Select><Select value={market} onValueChange={setMarket}><SelectTrigger aria-label="Фильтр по рынку"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">Все рынки</SelectItem><SelectItem value="futures">Фьючерсы</SelectItem><SelectItem value="spot">Спот</SelectItem></SelectContent></Select><button className="icon-button" aria-label="Скачать историю CSV" onClick={exportCsv}><Download size={17}/></button></div></div>
 <div className="calendar-heading"><div className="month-control"><h2>{monthTitle}</h2><div className="month-arrows"><button className="icon-button" aria-label="Предыдущий месяц" onClick={()=>move(-1)}><ChevronLeft size={19}/></button><button className="icon-button" aria-label="Следующий месяц" onClick={()=>move(1)}><ChevronRight size={19}/></button></div><button className="today-button" onClick={()=>setMonth(new Date(now.getFullYear(),now.getMonth(),1))}>Сегодня</button></div><div className="calendar-options"><span className="trading-days">{daily.filter(d=>d.rows.length).length} торговых дней</span><Tabs value={unit} onValueChange={v=>setUnit(v as "usd"|"percent")}><TabsList className="unit-tabs"><TabsTrigger value="percent" disabled={capitalUsd<=0} title={capitalUsd<=0?"Сначала синхронизируйте баланс биржи":undefined}>%</TabsTrigger><TabsTrigger value="usd">$</TabsTrigger></TabsList></Tabs></div></div>
 {unit==="percent"&&<p className="percentage-note">PnL рассчитан от {demo?"демо-капитала 25 000 $":`текущего общего капитала ${capitalUsd.toLocaleString("ru-RU",{style:"currency",currency:"USD",minimumFractionDigits:2})}`}. Общий капитал включает все подключённые счета.</p>}
 {mode==="calendar"?<div className="calendar"><div className="calendar-labels">{["Пн","Вт","Ср","Чт","Пт","Сб","Вс","За неделю"].map(d=><span key={d}>{d}</span>)}</div>{weeks.map((week,wi)=>{const wr=rows.filter(t=>week.includes(Number(t.date.slice(-2)))),valid=week.filter((d):d is number=>d!==null);return <div className="calendar-week" key={wi}>{week.map((day,i)=>{if(!day)return <div className="calendar-day outside" key={i}/>;const ds=daily[day-1].rows,v=sum(ds),key=dateKey(new Date(month.getFullYear(),month.getMonth(),day)),future=key>today;return <button key={i} disabled={future} className={`calendar-day ${ds.length?sign(v):"no-trades"} ${key===today?"is-today":""}`} onClick={()=>openDay(day)} aria-label={`${day} ${months[month.getMonth()]}, ${ds.length?money(v):"нет сделок"}`}><span className="day-top"><span className="day-number">{day}</span>{key===today&&<span className="today-tag">Сегодня</span>}</span><strong><span className="desktop-value">{ds.length?fmt(v):"—"}</span><span className="mobile-value">{ds.length?(unit==="percent"?fmtPercent(v,1):`${v>0?"+":v<0?"−":""}${Math.round(Math.abs(v)/100)}`):"—"}</span></strong><span className="day-count">{ds.length?`${ds.length} ${recordLabel}`:future?"":"Нет сделок"}</span>{ds.length>0&&<div className="day-meter"><i style={{width:`${Math.max(8,Math.abs(v)/maxDaily*100)}%`}}/></div>}</button>})}<button className="week-total" onClick={()=>open({start:dateKey(new Date(month.getFullYear(),month.getMonth(),valid[0])),end:dateKey(new Date(month.getFullYear(),month.getMonth(),valid[valid.length-1])),title:`${valid[0]}–${valid[valid.length-1]} · ${monthTitle}`})}><span>Неделя {wi+1}</span><strong className={sign(sum(wr))}>{fmt(sum(wr))}</strong><small>{wr.length} {recordLabel}</small><ArrowUpRight size={14}/></button></div>})}<button className="month-total" onClick={()=>open({start:first,end:last,title:monthTitle})}><span>Итого за месяц</span><strong className={sign(total)}>{fmt(total)}</strong><small>{rows.length} {recordLabel}</small><ArrowUpRight size={14}/></button></div>:<div className="history-content">{demo?<TradeTable rows={rows} unit={unit} capitalUsd={capitalUsd}/>:<RealHistory from={first} to={last} exchange={exchange} market={market}/>}</div>}
 <div className="calendar-footer"><div className="legend"><span><i className="profit"/>Прибыль</span><span><i className="loss"/>Убыток</span><span><i/>Нет сделок</span></div><span>Нажмите на день, чтобы открыть статистику<ArrowUpRight size={13}/></span></div></section>
 <AccountAnalytics enabled={!demo} unit={unit} capitalUsd={capitalUsd}/>
 <section className="bottom-grid"><div className="panel"><div className="panel-heading"><h2>Динамика PnL</h2><span>Накопительный результат · {unit==="percent"?"%":"$"}</span></div><div className="chart-total"><Amount value={total} unit={unit} capitalUsd={capitalUsd}/><span>за выбранный месяц</span></div><Trend rows={rows} days={days}/></div><div className="panel exchange-panel"><div className="panel-heading"><h2>По биржам</h2><span>{monthTitle}</span></div><div className="exchange-list">{group(rows,"exchange").map(([name,value,count])=><button className="exchange-row" key={name} onClick={()=>{open({start:first,end:last,title:monthTitle});setDetailExchange(name)}}><ExchangeIcon name={name}/><span className="exchange-name">{name}<small>{count} {recordLabel}</small></span><Amount value={value} unit={unit} capitalUsd={capitalUsd}/><ChevronRight size={14}/></button>)}{!rows.length&&<div className="empty-state">Нет сделок за этот период</div>}</div></div></section><footer className="app-footer"><span>Личный торговый журнал</span><span>PnL после комиссий и финансирования · UTC</span></footer></main>
 <Dialog open={!!period} onOpenChange={v=>{if(!v)setPeriod(null)}}><DialogContent className="detail-dialog" showCloseButton={false}><div className="detail-top"><div><div className="eyebrow">СТАТИСТИКА ПЕРИОДА</div><DialogTitle>{period?.title}</DialogTitle><DialogDescription>Реализованный PnL · {unit==="percent"?"% от общего капитала":"USD"} · {demo?"демоданные":"данные бирж"}</DialogDescription></div><DialogClose className="icon-button" aria-label="Закрыть статистику"><X size={21}/></DialogClose></div><div className="detail-result"><span>Результат {detailExchange!=="all"?`· ${detailExchange}`:""}</span><strong><Amount value={sum(details)} unit={unit} capitalUsd={capitalUsd}/></strong><span>{details.length} {recordLabel} · {new Set(details.map(t=>t.ticker)).size} тикеров</span></div><Tabs defaultValue="breakdown"><TabsList className="view-tabs"><TabsTrigger value="breakdown">Разбивка PnL</TabsTrigger><TabsTrigger value="trades">{demo?"Сделки":"Записи PnL"}</TabsTrigger></TabsList><TabsContent value="breakdown"><div className="breakdown-grid"><section><h3>По биржам</h3><button className={"all-exchanges "+(detailExchange==="all"?"selected":"")} onClick={()=>setDetailExchange("all")}>Все биржи<Amount value={sum(selected)} unit={unit} capitalUsd={capitalUsd}/></button>{group(selected,"exchange").map(([name,v])=><button className={"exchange-row selectable "+(detailExchange===name?"selected":"")} key={name} onClick={()=>setDetailExchange(name)}><ExchangeIcon name={name}/><span className="exchange-name">{name}</span><Amount value={v} unit={unit} capitalUsd={capitalUsd}/></button>)}</section><section><h3>По тикерам <span>{detailExchange==="all"?"Все биржи":detailExchange}</span></h3>{group(details,"ticker").map(([name,v,count])=><div className="ticker-row" key={name}><span className="coin-icon">{name.slice(0,1)}</span><span>{name}<small>{count} {recordLabel}</small></span><Amount value={v} unit={unit} capitalUsd={capitalUsd}/></div>)}</section></div>{!details.length&&<div className="empty-state"><CalendarDays size={28}/><h3>За этот период сделок нет</h3><p>Выберите другой день или биржу.</p></div>}<div className="result-summary"><h3>Сводка</h3><div><span>PnL сделок</span><Amount value={details.reduce((s,t)=>s+t.gross,0)} unit={unit} capitalUsd={capitalUsd}/></div><div><span>Комиссии</span><Amount value={-details.reduce((s,t)=>s+t.fee,0)} unit={unit} capitalUsd={capitalUsd}/></div><div><span>Финансирование</span><Amount value={details.reduce((s,t)=>s+t.funding,0)} unit={unit} capitalUsd={capitalUsd}/></div><div className="summary-total"><span>Результат</span><Amount value={sum(details)} unit={unit} capitalUsd={capitalUsd}/></div></div></TabsContent><TabsContent value="trades"><TradeTable rows={details} unit={unit} capitalUsd={capitalUsd}/></TabsContent></Tabs><button className="secondary-button" onClick={exportCsv}><Download size={16}/>Скачать CSV</button></DialogContent></Dialog>
 <Dialog open={connectionOpen} onOpenChange={setConnectionOpen}><DialogContent className="info-dialog connection-dialog"><DialogTitle>Подключения к биржам</DialogTitle><DialogDescription>Ключи только для чтения. История сохраняется на вашем сервере.</DialogDescription><Connections onChange={()=>{setDemo(false);server.refresh()}}/></DialogContent></Dialog>
 <Dialog open={installOpen} onOpenChange={setInstallOpen}><DialogContent className="info-dialog"><DialogTitle>Журнал на главном экране</DialogTitle><DialogDescription>Откройте приложение в браузере на телефоне.</DialogDescription><h3>iPhone / iPad</h3><p>В Safari нажмите «Поделиться» → «На экран Домой». Оставьте включённым «Открывать как веб-приложение».</p><h3>Android</h3><p>В меню Chrome выберите «Добавить на главный экран» или «Установить приложение».</p><p className="info-note">Для первого открытия нужен интернет. Офлайн доступен экран с подсказкой; финансовые данные не кэшируются.</p></DialogContent></Dialog></div>;
}
function TradeTable({rows,unit="usd",capitalUsd=0}:{rows:Trade[];unit?:"usd"|"percent";capitalUsd?:number}){return rows.length?<Table><TableHeader><TableRow>{["Дата · UTC","Биржа","Тикер","Рынок","Комиссия","Результат"].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{[...rows].sort((a,b)=>b.date.localeCompare(a.date)).map(t=><TableRow key={t.id}><TableCell>{t.date.slice(5).split("-").reverse().join(".")}</TableCell><TableCell>{t.exchange}</TableCell><TableCell><strong>{t.ticker}</strong><span className="settle"> / {t.settle}</span></TableCell><TableCell>{t.market==="spot"?"Спот":"Фьючерсы"}</TableCell><TableCell><span className="negative">{t.fee?money(-t.fee):"—"}</span></TableCell><TableCell><span className={sign(sum([t]))}>{unit==="usd"?money(sum([t])):`${sum([t])>0?"+":sum([t])<0?"−":""}${Math.abs(percentOfCapital(sum([t]),capitalUsd)).toFixed(2)}%`}</span></TableCell></TableRow>)}</TableBody></Table>:<div className="empty-state">Нет сделок за выбранный период</div>}
function Trend({rows,days}:{rows:Trade[];days:number}){let s=0;const points=Array.from({length:days},(_,i)=>{s+=sum(rows.filter(t=>Number(t.date.slice(-2))===i+1));return s/100}),low=Math.min(0,...points),high=Math.max(1,...points),coords=points.map((v,i)=>`${20+i/(days-1)*660},${140-(v-low)/(high-low)*118}`);return <div className="trend"><svg viewBox="0 0 720 180" role="img" aria-label={`Накопительный PnL: ${money(sum(rows))}`}><defs><linearGradient id="chart-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#b4d990" stopOpacity=".19"/><stop offset="100%" stopColor="#b4d990" stopOpacity="0"/></linearGradient></defs>{[25,65,105,145].map(y=><line key={y} x1="20" x2="690" y1={y} y2={y} stroke="#ffffff09" strokeDasharray="3 5"/>)}<path d={`M20,145 L${coords.join(" L")} L680,145 Z`} fill="url(#chart-fill)"/><polyline points={coords.join(" ")} fill="none" stroke="#bbdf98" strokeWidth="2.4" strokeLinejoin="round"/>{[1,Math.round(days/3),Math.round(days*2/3),days].map(n=><text key={n} x={20+(n-1)/(days-1)*660} y="174" fill="#7f858d" fontSize="12" textAnchor="middle">{n}</text>)}</svg></div>}

