"use client";
import { useCallback, useEffect, useState } from 'react';
import { Check, ChevronDown, Eye, EyeOff, ImagePlus, Pencil, Save, Trash2, WalletCards } from 'lucide-react';
import { percentOfCapital, type Trade } from '@/lib/journal';

type Connection={id:string;exchange:string;label:string;start:number;status:string;error:string|null;synced:number|null;records:number;earliest:number|null;disabled:number};
type Provider={id:string;enabled:boolean;address?:boolean;passphrase?:boolean;notice:string};
export async function journalApi<T = {ok:boolean}>(path:string,body?:unknown):Promise<T> {
  const res=await fetch('/api/journal'+path,{method:body===undefined?'GET':'POST',credentials:'same-origin',cache:'no-store',headers:body===undefined?{}:{'Content-Type':'application/json','X-Journal-Request':'1'},...(body===undefined?{}:{body:JSON.stringify(body)})});
  if(!res.headers.get('content-type')?.includes('application/json'))throw new Error('Сервер журнала пока недоступен.');
  const data=await res.json() as T & {error?:string};if(!res.ok)throw new Error(data.error||'Ошибка сервера.');return data;
}

type NoteImage={id:string;name:string;mime:string;size:number;created:number};
const imageTypes=['image/png','image/jpeg','image/webp'];
const maxDayImages=10;
function fileBase64(file:File){return new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]||'');reader.onerror=()=>reject(new Error('Не удалось прочитать изображение.'));reader.readAsDataURL(file);});}
function pastedImages(data:DataTransfer){const itemFiles=Array.from(data.items).filter(item=>item.kind==='file'&&item.type.startsWith('image/')).map(item=>item.getAsFile()).filter((file):file is File=>!!file);return itemFiles.length?itemFiles:Array.from(data.files).filter(file=>file.type.startsWith('image/'));}
function LinkedNote({text}:{text:string}){return <div className="day-note-text">{text.split(/(https?:\/\/[^\s]+)/g).map((part,i)=>part.startsWith('http://')||part.startsWith('https://')?<a key={i} href={part} target="_blank" rel="noreferrer">{part}</a>:<span key={i}>{part}</span>)}</div>}
export function DailyNote({date}:{date:string}){
  const [note,setNote]=useState(''),[draft,setDraft]=useState(''),[images,setImages]=useState<NoteImage[]>([]),[editing,setEditing]=useState(false),[busy,setBusy]=useState(false),[status,setStatus]=useState(''),[error,setError]=useState('');
  useEffect(()=>{let active=true;setBusy(true);setError('');journalApi<{note:string;images:NoteImage[]}>(`/notes/${date}`).then(v=>{if(active){setNote(v.note);setDraft(v.note);setImages(v.images);setEditing(!v.note&&!v.images.length);}}).catch(e=>{if(active)setError((e as Error).message)}).finally(()=>{if(active)setBusy(false)});return()=>{active=false}},[date]);
  async function save(){setBusy(true);setError('');setStatus('');try{await journalApi(`/notes/${date}`,{note:draft});setNote(draft);setEditing(false);setStatus('Сохранено');}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  const upload=useCallback(async(files:File[])=>{if(!files.length||busy)return;const available=maxDayImages-images.length;if(available<=0){setError('Для одного дня можно сохранить не больше 10 скриншотов.');return}if(files.length>available){setError(`Можно добавить ещё ${available} ${available===1?'скриншот':'скриншота'}.`);return}setBusy(true);setError('');setStatus('');try{const added:NoteImage[]=[];for(const file of files){if(!imageTypes.includes(file.type))throw new Error('Поддерживаются PNG, JPEG и WebP.');if(file.size>5*1024*1024)throw new Error('Размер одного изображения не должен превышать 5 МБ.');const generic=!file.name||/^image\.(png|jpe?g|webp)$/i.test(file.name);const name=generic?`Скриншот ${new Date().toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit',second:'2-digit'})}.${file.type.split('/')[1].replace('jpeg','jpg')}`:file.name;added.push(await journalApi<NoteImage>(`/notes/${date}/images`,{name,mime:file.type,data:await fileBase64(file)}));}setImages(v=>[...v,...added]);setStatus(added.length===1?'Скриншот добавлен':`Добавлено скриншотов: ${added.length}`);}catch(e){setError((e as Error).message)}finally{setBusy(false)}},[busy,date,images.length]);
  useEffect(()=>{const paste=(event:ClipboardEvent)=>{if(!event.clipboardData)return;const files=pastedImages(event.clipboardData);if(files.length){event.preventDefault();void upload(files)}};window.addEventListener('paste',paste);return()=>window.removeEventListener('paste',paste)},[upload]);
  async function remove(id:string){setBusy(true);setError('');try{await journalApi(`/notes/${date}/images/${id}/delete`,{});setImages(v=>v.filter(image=>image.id!==id));setStatus('Изображение удалено');}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  return <section className="day-note"><div className="day-note-head"><div><h3>Заметки за день</h3><p>Сохраните выводы, план или ссылку. Скриншот можно вставить через Ctrl+V.</p></div>{!editing&&<button className="day-note-action" onClick={()=>setEditing(true)}><Pencil size={15}/>{note?'Изменить':'Добавить заметку'}</button>}</div>
    {editing?<div className="day-note-editor"><textarea value={draft} maxLength={20000} autoFocus placeholder="Что произошло сегодня? Вставьте текст, ссылку или скриншот…" onChange={e=>setDraft(e.target.value)}/><div className="day-note-editor-foot"><span>{draft.length.toLocaleString('ru-RU')} / 20 000</span><button className="day-note-save" disabled={busy} onClick={save}><Save size={15}/>{busy?'Сохранение…':'Сохранить'}</button></div></div>:note?<LinkedNote text={note}/>:<button className="day-note-empty" onClick={()=>setEditing(true)}>Добавить запись о торговом дне</button>}
    {!!images.length&&<div className="day-note-gallery">{images.map(image=><figure key={image.id}><a href={`/api/journal/notes/${date}/images/${image.id}`} target="_blank" rel="noreferrer"><img src={`/api/journal/notes/${date}/images/${image.id}`} alt={image.name}/></a><figcaption title={image.name}><span>{image.name}</span><button aria-label={`Удалить ${image.name}`} disabled={busy} onClick={()=>void remove(image.id)}><Trash2 size={14}/></button></figcaption></figure>)}</div>}
    <div className="day-note-tools"><label className={busy||images.length>=maxDayImages?'disabled':''}><ImagePlus size={16}/>{busy?'Загрузка…':'Добавить скриншоты'}<input type="file" accept="image/png,image/jpeg,image/webp" multiple disabled={busy||images.length>=maxDayImages} onChange={e=>{void upload(Array.from(e.target.files||[]));e.currentTarget.value=''}}/></label><span>Ctrl+V · PNG, JPEG или WebP · до 5 МБ · {images.length}/{maxDayImages}</span>{status&&<span className="day-note-status"><Check size={14}/>{status}</span>}</div>{error&&<p role="alert" className="server-error">{error}</p>}
  </section>;
}
export function useServerJournal(from:string,to:string,enabled:boolean) {
  const [rows,setRows]=useState<Trade[]>([]),[notice,setNotice]=useState(''),[error,setError]=useState(''),[revision,setRevision]=useState(0);
  useEffect(()=>{if(!enabled){setRows([]);return;}let active=true;setRows([]);
    async function load(){try{const now=Date.now(),a=new Date(now-7*86400000).toISOString().slice(0,10),b=new Date(now+7*86400000).toISOString().slice(0,10);const [data,recent]=await Promise.all([journalApi<{rows:Trade[];notice:string;unvalued:number}>(`/journal?from=${from}&to=${to}`),journalApi<{rows:Trade[]}>(`/journal?from=${a}&to=${b}`)]);data.rows=[...new Map([...data.rows,...recent.rows].map(r=>[r.id,r])).values()];if(active){setRows(data.rows);setNotice(data.notice+(data.unvalued?` ${data.unvalued} записей в других валютах не включены в USD-итог.`:''));setError('');}}catch(e){if(active)setError((e as Error).message);}}
    void load();const timer=setInterval(load,10000);return()=>{active=false;clearInterval(timer);};
  },[from,to,enabled,revision]);
  return {rows,notice,error,refresh:()=>setRevision(v=>v+1)};
}
export function useAllServerJournal(enabled:boolean) {
  const [rows,setRows]=useState<Trade[]>([]),[error,setError]=useState('');
  useEffect(()=>{if(!enabled){setRows([]);setError('');return;}let active=true;
    async function load(){try{const data=await journalApi<{rows:Trade[]}>('/journal?scope=all');if(active){setRows(data.rows);setError('');}}catch(e){if(active)setError((e as Error).message);}}
    void load();const timer=setInterval(load,30000);return()=>{active=false;clearInterval(timer);};
  },[enabled]);
  return {rows,error};
}
type CapitalAccount={exchange:string;label:string;time:number;equityUsd:string;warning:string|null};
export type PortfolioCapital={totalEquityUsd:string;updatedAt:number|null;accounts:CapitalAccount[]};
export function usePortfolioCapital(enabled:boolean) {
  const [data,setData]=useState<PortfolioCapital|null>(null),[error,setError]=useState('');
  useEffect(()=>{if(!enabled){setData(null);setError('');return;}let active=true;async function load(){try{const v=await journalApi<PortfolioCapital>('/balances');if(active){setData(v);setError('');}}catch(e){if(active)setError((e as Error).message);}}void load();const timer=setInterval(load,30000);return()=>{active=false;clearInterval(timer);};},[enabled]);
  return {data,error};
}
export function CapitalCard({data,error}:{data:PortfolioCapital|null;error:string}) {
  const [hidden,setHidden]=useState(true),[expanded,setExpanded]=useState(false);
  const toggle=()=>setHidden(v=>!v);
  const total=Number(data?.totalEquityUsd||0).toLocaleString('ru-RU',{style:'currency',currency:'USD',minimumFractionDigits:2});
  const count=data?.accounts?.length||0;
  const balances=(data?.accounts||[]).reduce<Array<{exchange:string;equity:number;accounts:number}>>((result,account)=>{const current=result.find(v=>v.exchange===account.exchange);if(current){current.equity+=Number(account.equityUsd||0);current.accounts+=1;}else result.push({exchange:account.exchange,equity:Number(account.equityUsd||0),accounts:1});return result;},[]);
  const format=(value:number)=>value.toLocaleString('ru-RU',{style:'currency',currency:'USD',minimumFractionDigits:2});
  return <div className="capital-popover"><section className="capital-card" aria-label="Общий капитал"><button className="capital-card-main" onClick={()=>setExpanded(v=>!v)} aria-expanded={expanded} aria-controls="capital-breakdown"><WalletCards size={18}/><span className="capital-copy"><span>Общий капитал</span><strong aria-label={hidden?'Капитал скрыт':total}>{hidden?'•••••• $':count?total:'—'}</strong><small>{error?'Не удалось обновить':count?`${count} подключений · обновлено ${new Date(data?.updatedAt||0).toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'})}`:'Подключите биржу'}</small></span></button><div className="capital-actions"><button className="icon-button" onClick={toggle} aria-label={hidden?'Показать капитал':'Скрыть капитал'}>{hidden?<Eye size={17}/>:<EyeOff size={17}/>}</button><button className="icon-button" onClick={()=>setExpanded(v=>!v)} aria-label={expanded?'Скрыть балансы бирж':'Показать балансы бирж'} aria-expanded={expanded}><ChevronDown className={expanded?'expanded':''} size={17}/></button></div></section>{expanded&&<div id="capital-breakdown" className="capital-breakdown"><div className="capital-breakdown-head"><span>Баланс по биржам</span><small>{balances.length} {balances.length===1?'биржа':'бирж'}</small></div>{balances.map(item=><div className="capital-balance-row" key={item.exchange}><span><b>{item.exchange}</b>{item.accounts>1&&<small>{item.accounts} счёта</small>}</span><strong aria-label={hidden?'Баланс скрыт':format(item.equity)}>{hidden?'•••••• $':format(item.equity)}</strong></div>)}{!balances.length&&<p>После синхронизации здесь появятся балансы.</p>}<div className="capital-breakdown-total"><span>Общий капитал</span><strong>{hidden?'•••••• $':count?total:'—'}</strong></div></div>}</div>;
}
export function AccountAnalytics({enabled,unit,capitalUsd}:{enabled:boolean;unit:'usd'|'percent';capitalUsd:number}) {
  const [period,setPeriod]=useState<'day'|'week'|'month'|'year'>('month'),[rows,setRows]=useState<Trade[]>([]),[accounts,setAccounts]=useState<Array<CapitalAccount&{availableUsd:string|null}>>([]);
  useEffect(()=>{if(!enabled)return;let active=true;const now=new Date(),from=`${now.getUTCFullYear()}-01-01`,to=`${now.getUTCFullYear()}-12-31`;async function load(){try{const [journal,capital]=await Promise.all([journalApi<{rows:Trade[]}>(`/journal?from=${from}&to=${to}`),journalApi<{accounts?:Array<CapitalAccount&{availableUsd:string|null}>}>('/balances')]);if(active){setRows(journal.rows);setAccounts(capital.accounts||[]);}}catch{}}void load();const timer=setInterval(load,30000);return()=>{active=false;clearInterval(timer);};},[enabled]);
  if(!enabled)return null;const now=new Date(),today=now.toISOString().slice(0,10),week=new Date(now);week.setUTCDate(now.getUTCDate()-((now.getUTCDay()+6)%7));const start=period==='day'?today:period==='week'?week.toISOString().slice(0,10):period==='month'?today.slice(0,7)+'-01':today.slice(0,4)+'-01-01',filtered=rows.filter(v=>v.date>=start&&v.date<=today),net=filtered.reduce((s,v)=>s+v.gross-v.fee+v.funding,0),fees=filtered.reduce((s,v)=>s+v.fee,0),funding=filtered.reduce((s,v)=>s+v.funding,0),wins=filtered.filter(v=>v.gross-v.fee+v.funding>0).length,winrate=filtered.length?wins/filtered.length*100:0,usd=(c:number)=>new Intl.NumberFormat('ru-RU',{style:'currency',currency:'USD'}).format(c/100),display=(c:number)=>unit==='usd'?usd(c):`${c>0?'+':c<0?'−':''}${Math.abs(percentOfCapital(c,capitalUsd)).toFixed(2)}%`;
  const exchangeRows=accounts.map(a=>{const rr=filtered.filter(v=>v.exchange===a.exchange),profit=rr.reduce((s,v)=>s+v.gross-v.fee+v.funding,0),commission=rr.reduce((s,v)=>s+v.fee,0),fund=rr.reduce((s,v)=>s+v.funding,0);return {...a,profit,commission,fund};});
  return <section className="account-analytics"><div className="analytics-head"><h2>Статистика счетов</h2><div className="period-switch">{([['day','Сегодня'],['week','Неделя'],['month','Месяц'],['year','Год']] as const).map(([id,label])=><button key={id} className={period===id?'active':''} onClick={()=>setPeriod(id)}>{label}</button>)}</div></div><div className="metric-strip"><div><span>Чистый PnL</span><strong className={net>=0?'positive':'negative'}>{display(net)}</strong></div><div><span>Комиссии</span><strong className="negative">{display(-fees)}</strong></div><div><span>Финансирование</span><strong>{display(funding)}</strong></div><div><span>Винрейт</span><strong>{winrate.toFixed(1)}%</strong></div><div><span>Записи PnL</span><strong>{filtered.length}</strong></div></div><div className="accounts-table-wrap"><table className="accounts-table"><thead><tr><th>Биржа / счёт</th><th>Капитал</th><th>Результат</th><th>Комиссия</th><th>Фандинг</th></tr></thead><tbody>{exchangeRows.map(a=><tr key={a.exchange+a.label}><td><b>{a.exchange}</b><small>{a.label}</small></td><td>{Number(a.equityUsd).toLocaleString('ru-RU',{style:'currency',currency:'USD'})}</td><td className={a.profit>=0?'positive':'negative'}>{display(a.profit)}</td><td className="negative">{a.commission?display(-a.commission):'—'}</td><td>{display(a.fund)}</td></tr>)}</tbody></table>{!accounts.length&&<p className="empty-state">После первой синхронизации здесь появятся капитал и статистика каждого счёта.</p>}</div></section>;
}
export function OwnerAccess({onOpen}:{onOpen:()=>void}) {
  const [state,setState]=useState<'loading'|'setup'|'login'|'error'>('loading'),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  useEffect(()=>{journalApi<{authenticated:boolean;needsSetup:boolean}>('/session').then(v=>{if(v.authenticated)onOpen();else setState(v.needsSetup?'setup':'login');}).catch(()=>{setState('error');setError('Сервер недоступен. Запустите npm run dev:api или проверьте хостинг.');});},[onOpen]);
  return <div className="owner-access"><div className="panel"><h1>Торговый журнал</h1><p>{state==='setup'?'Задайте пароль личного журнала. Регистрация не нужна.':state==='loading'?'Подключение к серверу…':'Введите пароль для доступа к биржевым данным.'}</p>{state!=='loading'&&state!=='error'&&<form className="connection-form" onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;setBusy(true);setError('');const data=new FormData(form);try{await journalApi(state==='setup'?'/setup':'/login',{password:data.get('password'),token:data.get('token')});form.reset();onOpen();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>{state==='setup'&&<label>Код первоначальной настройки<input name="token" type="password" autoComplete="off" required/><small>Локально: файл .journal-local/SETUP.txt. На Railway: переменная JOURNAL_SETUP_TOKEN.</small></label>}<label>Пароль журнала<input name="password" type="password" minLength={12} maxLength={256} autoComplete={state==='setup'?'new-password':'current-password'} required/></label><button className="connect-button" disabled={busy}>{busy?'Проверка…':state==='setup'?'Создать личный журнал':'Открыть журнал'}</button></form>}{error&&<p role="alert" className="server-error">{error}</p>}</div></div>;
}
export function Connections({onChange}:{onChange:()=>void}) {
  const [items,setItems]=useState<Connection[]>([]),[providers,setProviders]=useState<Provider[]>([]),[exchange,setExchange]=useState('Bybit'),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const selected=providers.find(v=>v.id===exchange);
  async function load(){const data=await journalApi<{connections:Connection[];catalog:Provider[]}>('/connections');setItems(data.connections);setProviders(data.catalog);}
  useEffect(()=>{void load().catch(e=>setError(e.message));const timer=setInterval(()=>void load().catch(()=>{}),4000);return()=>clearInterval(timer);},[]);
  const labels:Record<string,string>={queued:'В очереди',syncing:'Загружаем историю',retrying:'Ожидаем биржу',ready:'Доступная история загружена',error:'Нужна проверка'};
  async function action(c:Connection,verb:string){setError('');try{await journalApi(`/connections/${c.id}/${verb}`,{});await load();onChange();}catch(e){setError((e as Error).message);}}
  return <div className="server-connections"><div className="saved-connections">{items.map(c=><section className="saved-connection" key={c.id}><strong>{c.exchange} · {c.label}</strong><span>{c.disabled?'Приостановлено':labels[c.status]||c.status}</span><small>{c.records.toLocaleString('ru-RU')} записей{c.earliest?` · с ${new Date(c.earliest).toLocaleDateString('ru-RU')}`:''}</small>{c.synced&&<small>Обновлено: {new Date(c.synced).toLocaleString('ru-RU')}</small>}{c.error&&<p role="alert">{c.error}</p>}<div className="connection-actions"><button className="secondary-button" onClick={()=>void action(c,'sync')}>Синхронизировать</button><button className="secondary-button" onClick={()=>void action(c,c.disabled?'resume':'pause')}>{c.disabled?'Продолжить':'Пауза'}</button><button className="secondary-button danger-button" onClick={()=>{if(window.confirm('Удалить подключение и всю загруженную историю этого счёта?'))void action(c,'delete')}}>Удалить</button></div></section>)}</div>
    <form className="connection-form" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');const form=e.currentTarget;const data=new FormData(form);try{await journalApi('/connections',{exchange,label:data.get('label'),apiKey:data.get('apiKey'),secret:data.get('secret'),passphrase:data.get('passphrase'),address:data.get('address'),start:data.get('start'),spotSymbols:data.get('spotSymbols'),futures:data.get('futures')==='on'});form.reset();await load();onChange();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>
    <h3>Добавить подключение</h3><label>Биржа<select value={exchange} onChange={e=>setExchange(e.target.value)}>{providers.map(v=><option key={v.id} value={v.id} disabled={!v.enabled}>{v.id}{!v.enabled?' — скоро':''}</option>)}</select></label>
    <p className="info-note">{selected?.notice}</p><label>Название счёта<input name="label" placeholder="Основной счёт" maxLength={80} required/></label>
    {selected?.address?<label>Публичный адрес кошелька<input name="address" placeholder="0x…" pattern="0x[a-fA-F0-9]{40}" autoComplete="off" required/><small>Не вводите seed-фразу или приватный ключ.</small></label>:<><label>{exchange==='Aster'?'API Wallet Address':'API Key'}<input name="apiKey" type="password" autoComplete="off" maxLength={256} placeholder={exchange==='Aster'?'0x…':undefined} required/></label><label>{exchange==='Aster'?'API Wallet Private Key':'API Secret'}<input name="secret" type="password" autoComplete="off" maxLength={512} placeholder={exchange==='Aster'?'Никому не передавайте этот ключ':undefined} required/>{exchange==='Aster'&&<small>Только ключ отдельного API Wallet с Permission: Read. Никогда не вводите ключ основного кошелька.</small>}</label>{selected?.passphrase&&<label>API Passphrase<input name="passphrase" type="password" autoComplete="off" maxLength={256} required/></label>}</>}
    <label>Начало истории<input name="start" type="date" min="2017-01-01" max={new Date().toISOString().slice(0,10)} defaultValue="2024-01-01" required/></label>
    {exchange==='Binance'&&<><label className="check-label"><input name="futures" type="checkbox" defaultChecked/>USDⓈ-M фьючерсы</label><p className="info-note">Spot включён автоматически. Сервер сам проверит доступные пары Binance и загрузит найденную историю; при первом подключении это может занять несколько минут.</p></>}
    {exchange==='MEXC'&&<><label className="check-label"><input name="futures" type="checkbox" defaultChecked/>USDT/USDC фьючерсы</label><label>Все торговавшиеся пары<input name="spotSymbols" placeholder="BTCUSDT, ETHUSDT, SOLUSDC" required/><small>Пары используются для spot и futures; spot API отдаёт историю только за последний месяц.</small></label></>}
    <label className="check-label"><input type="checkbox" required/>{selected?.address?'Я указал только публичный адрес, без seed-фразы и приватного ключа.':'Ключ только для чтения, без торговли, переводов и вывода.'}</label>
    <button className="connect-button" disabled={busy||!selected?.enabled}>{busy?'Проверяем доступ…':'Подключить и загрузить историю'}</button>
    {error&&<p role="alert" className="server-error">{error}</p>}
    <small>{selected?.address?'Публичный адрес не даёт доступа к средствам. Синхронизация продолжается после закрытия страницы.':'Секрет отправляется только вашему серверу, хранится зашифрованным и не возвращается в браузер. Синхронизация продолжается после закрытия страницы.'}</small>
    </form></div>;
}
export function RealHistory({from,to,exchange,market}:{from:string;to:string;exchange:string;market:string}) {
  const [rows,setRows]=useState<Array<{id:string;time:number;exchange:string;symbol:string;market:string;side:string;quantity:string;price:string;fee:string;currency:string}>>([]),[offset,setOffset]=useState(0),[more,setMore]=useState(false),[error,setError]=useState('');
  useEffect(()=>setOffset(0),[from,to]);
  useEffect(()=>{let active=true;async function load(){try{const data=await journalApi<{rows:typeof rows;hasMore:boolean}>(`/fills?from=${from}&to=${to}&offset=${offset}`);if(active){setRows(data.rows);setMore(data.hasMore);setError('');}}catch(e){if(active)setError((e as Error).message);}}void load();const timer=setInterval(load,10000);return()=>{active=false;clearInterval(timer);};},[from,to,offset]);
  const filtered=rows.filter(v=>(exchange==='all'||exchange===v.exchange)&&(market==='all'||market===v.market));
  return <div><p className="info-note">Исполнения биржи. Цена и комиссия — в исходных валютах; прибыль spot здесь не рассчитывается. Фильтры применяются к текущей странице.</p>{error&&<p role="alert">{error}</p>}<table className="real-history"><thead><tr>{['Дата · UTC','Биржа','Тикер','Сторона','Количество','Цена','Комиссия'].map(v=><th key={v}>{v}</th>)}</tr></thead><tbody>{filtered.map((v,i)=><tr key={v.exchange+v.id+i}><td>{new Date(v.time).toISOString().replace('T',' ').slice(0,19)}</td><td>{v.exchange}</td><td>{v.symbol}</td><td>{v.side}</td><td>{v.quantity}</td><td>{v.price}</td><td>{v.fee} {v.currency}</td></tr>)}</tbody></table>{!filtered.length&&<p className="empty-state">Нет исполнений на этой странице</p>}<div className="connection-actions"><button className="secondary-button" disabled={!offset} onClick={()=>setOffset(v=>Math.max(0,v-200))}>Назад</button><button className="secondary-button" disabled={!more} onClick={()=>setOffset(v=>v+200)}>Далее</button></div></div>;
}


