"use client";
import { useEffect,useMemo,useRef,useState } from 'react';
import type { CandlestickData,SeriesMarker,UTCTimestamp } from 'lightweight-charts';
import { ArrowLeft,ChartCandlestick,Clock3,Maximize2,Minimize2,X } from 'lucide-react';
import { journalApi } from './journal-server';
import { DialogClose } from './ui/dialog';

type Execution={id:string;time:number;side:'BUY'|'SELL';price:number;quantity:number;pnl:number;fee:number};
type Trade={id:string;exchange:string;account:string;symbol:string;market:'spot'|'futures';direction:'long'|'short'|'unknown';entryTime:number;exitTime:number|null;entryPrice:number;exitPrice:number;pnl:number;fee:number;complete:boolean;entries?:Execution[];exits?:Execution[];executions:Execution[]};
type Candle={time:number;open:number;high:number;low:number;close:number;volume:number};
const intervals=[['1s',1000],['5s',5000],['15s',15000],['1m',60000],['5m',300000],['1h',3600000],['1D',86400000]] as const;
const money=(value:number)=>`${value>=0?'+':'−'}$${Math.abs(value).toFixed(2)}`;
const time=(value:number)=>new Date(value).toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit',second:'2-digit',timeZone:'UTC'});

function TradeChart({trade}:{trade:Trade}){
  const [interval,setIntervalValue]=useState(1000),[candles,setCandles]=useState<Candle[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[expanded,setExpanded]=useState(false),[hover,setHover]=useState<{time:number;open:number;high:number;low:number;close:number}|null>(null),host=useRef<HTMLDivElement|null>(null),resetChart=useRef<(()=>void)|null>(null);
  const bounds=useMemo(()=>{const centerStart=trade.entryTime||trade.exitTime||0,centerEnd=trade.exitTime||centerStart,padding=interval===86400000?30*86400000:interval===3600000?2*86400000:interval===300000?3*3600000:interval>=60000?3600000:5*60000,maxSpan=interval===86400000?120*86400000:interval===3600000?10*86400000:interval>=60000?2*86400000:3600000;let from=centerStart-padding,to=centerEnd+padding;if(to-from>maxSpan){from=centerStart-padding;to=from+maxSpan;}return {from,to};},[trade,interval]);
  useEffect(()=>{let active=true;journalApi<{candles:Candle[]}>(`/market-chart?exchange=${encodeURIComponent(trade.exchange)}&symbol=${encodeURIComponent(trade.symbol)}&market=${trade.market}&from=${bounds.from}&to=${bounds.to}&interval=${interval}`).then(v=>{if(active){setCandles(v.candles);setError('')}}).catch(e=>{if(active){setCandles([]);setError((e as Error).message)}}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[trade,bounds,interval]);
  useEffect(()=>{if(!host.current||!candles.length)return;let active=true,dispose=()=>{};void import('lightweight-charts').then(({CandlestickSeries,ColorType,CrosshairMode,LineStyle,createChart,createSeriesMarkers})=>{if(!active||!host.current)return;const data=candles.map(v=>({time:Math.floor(v.time/1000) as UTCTimestamp,open:v.open,high:v.high,low:v.low,close:v.close} as CandlestickData<UTCTimestamp>)),prices=candles.flatMap(v=>[v.high,v.low]),smallest=Math.min(...prices.filter(v=>v>0)),precision=Math.max(2,Math.min(8,Math.ceil(-Math.log10(smallest||1))+4)),chart=createChart(host.current,{autoSize:true,layout:{background:{type:ColorType.Solid,color:'#0d1525'},textColor:'#7f8da2',fontFamily:'Arial, Helvetica, sans-serif',fontSize:11,attributionLogo:false},grid:{vertLines:{color:'#1a2638',style:LineStyle.Solid},horzLines:{color:'#1a2638',style:LineStyle.Solid}},crosshair:{mode:CrosshairMode.Normal,vertLine:{color:'#718198',width:1,style:LineStyle.Dashed,labelBackgroundColor:'#273348'},horzLine:{color:'#718198',width:1,style:LineStyle.Dashed,labelBackgroundColor:'#273348'}},rightPriceScale:{visible:true,borderColor:'#2a3749',scaleMargins:{top:.08,bottom:.1}},leftPriceScale:{visible:false},timeScale:{borderColor:'#2a3749',timeVisible:true,secondsVisible:interval<60000,rightOffset:8,barSpacing:interval<60000?3.2:7,minBarSpacing:.5,fixLeftEdge:false,fixRightEdge:false},handleScroll:{mouseWheel:true,pressedMouseMove:true,horzTouchDrag:true,vertTouchDrag:false},handleScale:{mouseWheel:true,pinch:true,axisPressedMouseMove:{time:true,price:true},axisDoubleClickReset:{time:true,price:true}},localization:{timeFormatter:(value:unknown)=>new Date(Number(value)*1000).toLocaleString('ru-RU',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit',second:interval<60000?'2-digit':undefined,timeZone:'UTC'})}}),series=chart.addSeries(CandlestickSeries,{upColor:'#16d5ad',downColor:'#ff4e6a',borderVisible:false,wickUpColor:'#16d5ad',wickDownColor:'#ff5b70',priceLineVisible:false,lastValueVisible:true,priceFormat:{type:'price',precision,minMove:10**-precision}});series.setData(data);
    const nearestTime=(stamp:number)=>data.reduce((best,v)=>Math.abs(Number(v.time)*1000-stamp)<Math.abs(Number(best.time)*1000-stamp)?v:best,data[0]).time,markers:SeriesMarker<UTCTimestamp>[]=[...(trade.entries||[]).map((v):SeriesMarker<UTCTimestamp>=>({time:nearestTime(v.time),position:trade.direction==='short'?'aboveBar':'belowBar',color:trade.direction==='short'?'#ff5b70':'#20d98a',shape:trade.direction==='short'?'arrowDown':'arrowUp',text:'Вход'})),...(trade.exits||[]).map((v):SeriesMarker<UTCTimestamp>=>({time:nearestTime(v.time),position:trade.direction==='short'?'belowBar':'aboveBar',color:trade.direction==='short'?'#20d98a':'#ff5b70',shape:trade.direction==='short'?'arrowUp':'arrowDown',text:'Выход'}))].sort((a,b)=>Number(a.time)-Number(b.time));if(markers.length)createSeriesMarkers(series,markers,{autoScale:true});
    if(trade.entryPrice>0)series.createPriceLine({price:trade.entryPrice,color:trade.direction==='short'?'#ff5b70':'#20d98a',lineWidth:1,lineStyle:LineStyle.Dashed,axisLabelVisible:true,title:'Вход'});if(trade.exitPrice>0)series.createPriceLine({price:trade.exitPrice,color:trade.direction==='short'?'#20d98a':'#ff5b70',lineWidth:1,lineStyle:LineStyle.Dashed,axisLabelVisible:true,title:'Выход'});
    chart.subscribeCrosshairMove(param=>{if(!param.time){setHover(null);return}const value=param.seriesData.get(series) as CandlestickData<UTCTimestamp>|undefined;if(value)setHover({time:Number(param.time)*1000,open:value.open,high:value.high,low:value.low,close:value.close});});chart.timeScale().fitContent();resetChart.current=()=>{chart.priceScale('right').applyOptions({autoScale:true});chart.timeScale().fitContent();};dispose=()=>{resetChart.current=null;chart.remove();};});return()=>{active=false;dispose()}},[candles,interval,trade]);
  useEffect(()=>{if(!expanded)return;const close=(event:KeyboardEvent)=>{if(event.key==='Escape')setExpanded(false)};document.addEventListener('keydown',close);const previous=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.removeEventListener('keydown',close);document.body.style.overflow=previous}},[expanded]);
  const fmtPrice=(value:number)=>value?value.toLocaleString('ru-RU',{maximumFractionDigits:8}):'—',duration=trade.exitTime?Math.max(0,(trade.exitTime-trade.entryTime)/1000):0,quantity=(trade.entries||[]).reduce((n,v)=>n+v.quantity,0),intervalLabel=intervals.find(([,value])=>value===interval)?.[0]||'1s';
  return <section className={`trade-chart-card ${expanded?'chart-expanded':''}`}><div className="trade-chart-overview"><div><span>Результат</span><strong className={trade.pnl-trade.fee>=0?'positive':'negative'}>{money(trade.pnl-trade.fee)}</strong><small>PnL {money(trade.pnl)} · комиссия {money(-trade.fee)}</small></div><div><span>Позиция</span><strong>{trade.direction==='long'?'LONG':trade.direction==='short'?'SHORT':'—'}</strong><small>{fmtPrice(trade.entryPrice)} → {fmtPrice(trade.exitPrice)}{quantity?` · ${quantity}`:''}</small></div><div><span>Время · UTC</span><strong>{time(trade.entryTime)} → {trade.exitTime?time(trade.exitTime):'—'}</strong><small>{duration?`${duration<60?duration.toFixed(2)+'с':(duration/60).toFixed(1)+'м'} в позиции`:trade.exchange}</small></div></div><div className="trade-chart-toolbar"><button className="chart-auto" onClick={()=>resetChart.current?.()}><Clock3 size={13}/>Авто · {intervalLabel}</button><div className="trade-chart-actions"><div className="chart-intervals">{intervals.map(([label,value])=><button key={value} className={interval===value?'active':''} onClick={()=>{resetChart.current?.();if(interval!==value){setLoading(true);setIntervalValue(value)}}}>{label}</button>)}</div><button className="chart-expand" onClick={()=>setExpanded(v=>!v)} aria-label={expanded?'Свернуть график':'Развернуть график'}>{expanded?<Minimize2 size={16}/>:<Maximize2 size={16}/>}</button></div></div>
    <div className="trade-chart-wrap">{loading&&<div className="chart-message">Загружаю историю рынка…</div>}{!loading&&!candles.length&&<div className="chart-message"><ChartCandlestick size={28}/><strong>Данные графика пока недоступны</strong><span>{error||'Биржа не вернула свечи за выбранный период. Исполнения сделки показаны ниже.'}</span></div>}
      {!!candles.length&&<><div ref={host} className="lightweight-chart" role="img" aria-label={`Интерактивный свечной график ${trade.symbol}`}/>{hover&&<div className="chart-crosshair-data"><span>{new Date(hover.time).toLocaleString('ru-RU',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',timeZone:'UTC'})}</span><b>O {fmtPrice(hover.open)}</b><b>H {fmtPrice(hover.high)}</b><b>L {fmtPrice(hover.low)}</b><b>C {fmtPrice(hover.close)}</b></div>}</>}
    </div>
    <div className="trade-chart-foot"><div className="execution-strip">{trade.executions.length?trade.executions.map((v,i)=><div key={`${v.id}-${i}`}><span className={v.side==='BUY'?'buy':'sell'}>{v.side==='BUY'?'BUY':'SELL'}</span><strong>{v.quantity} × {v.price}</strong><small><Clock3 size={12}/>{time(v.time)} UTC</small></div>):<p>Биржа сохранила PnL, но не вернула цены исполнений для этой записи.</p>}</div><a href="https://www.tradingview.com/" target="_blank" rel="noreferrer">Charts by TradingView</a></div>
  </section>;
}

export function TradeExplorer({date,ticker,exchange,onBack}:{date:string;ticker:string;exchange:string;onBack:()=>void}){
  const [trades,setTrades]=useState<Trade[]>([]),[selected,setSelected]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState(''),[limited,setLimited]=useState(false);
  useEffect(()=>{let active=true;journalApi<{trades:Trade[];limited:boolean}>(`/trade-details?date=${date}&ticker=${encodeURIComponent(ticker)}&exchange=${encodeURIComponent(exchange)}`).then(v=>{if(active){setTrades(v.trades);setLimited(v.limited);setSelected(0);setError('')}}).catch(e=>{if(active)setError((e as Error).message)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[date,ticker,exchange]);
  const trade=trades[selected];return <div className="trade-explorer"><div className="trade-explorer-head"><button onClick={onBack}><ArrowLeft size={17}/>К разбивке</button><div><span>РАЗБОР СДЕЛОК · {date.split('-').reverse().join('.')}</span><h2>{ticker} <small>{exchange==='all'?'Все биржи':exchange}</small></h2></div><DialogClose className="icon-button trade-explorer-close" aria-label="Закрыть"><X size={20}/></DialogClose></div>
    {loading?<div className="empty-state">Загружаю исполнения…</div>:error?<div className="empty-state negative">{error}</div>:!trades.length?<div className="empty-state"><h3>Исполнения не найдены</h3><p>Запустите синхронизацию подключения. Новая версия загрузит цены и направления сделок.</p></div>:<><div className="trade-picker">{trades.map((v,i)=><button key={v.id} className={i===selected?'active':''} onClick={()=>setSelected(i)}><span>Сделка {i+1}<small>{v.exchange} · {time(v.exitTime||v.entryTime)} UTC</small></span><strong className={v.pnl-v.fee>=0?'positive':'negative'}>{money(v.pnl-v.fee)}</strong><em>{v.direction==='long'?'LONG':v.direction==='short'?'SHORT':'PNL'}</em></button>)}</div>{limited&&<p className="trade-data-note">Для старых записей доступны PnL и время. После синхронизации появятся цены входа, выхода и график.</p>}{trade&&<TradeChart key={trade.id} trade={trade}/>}</>}
  </div>;
}
