"use client";
import { useEffect,useMemo,useRef,useState,type PointerEvent as ReactPointerEvent,type WheelEvent as ReactWheelEvent } from 'react';
import { ArrowLeft,ChartCandlestick,Clock3,X } from 'lucide-react';
import { journalApi } from './journal-server';
import { DialogClose } from './ui/dialog';

type Execution={id:string;time:number;side:'BUY'|'SELL';price:number;quantity:number;pnl:number;fee:number};
type Trade={id:string;exchange:string;account:string;symbol:string;market:'spot'|'futures';direction:'long'|'short'|'unknown';entryTime:number;exitTime:number|null;entryPrice:number;exitPrice:number;pnl:number;fee:number;complete:boolean;entries?:Execution[];exits?:Execution[];executions:Execution[]};
type Candle={time:number;open:number;high:number;low:number;close:number;volume:number};
const intervals=[['1s',1000],['5s',5000],['15s',15000],['1m',60000],['5m',300000],['1h',3600000],['1D',86400000]] as const;
const money=(value:number)=>`${value>=0?'+':'−'}$${Math.abs(value).toFixed(2)}`;
const time=(value:number)=>new Date(value).toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit',second:'2-digit',timeZone:'UTC'});

function TradeChart({trade}:{trade:Trade}){
  const initialView={xz:1,yz:1,xc:.5,yc:.5},[interval,setIntervalValue]=useState(1000),[candles,setCandles]=useState<Candle[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[view,setView]=useState(initialView),drag=useRef<{x:number;y:number;view:typeof initialView}|null>(null);
  const bounds=useMemo(()=>{const centerStart=trade.entryTime||trade.exitTime||0,centerEnd=trade.exitTime||centerStart,padding=interval===86400000?30*86400000:interval===3600000?2*86400000:interval===300000?3*3600000:interval>=60000?3600000:5*60000,maxSpan=interval===86400000?120*86400000:interval===3600000?10*86400000:interval>=60000?2*86400000:3600000;let from=centerStart-padding,to=centerEnd+padding;if(to-from>maxSpan){from=centerStart-padding;to=from+maxSpan;}return {from,to};},[trade,interval]);
  useEffect(()=>{let active=true;journalApi<{candles:Candle[]}>(`/market-chart?exchange=${encodeURIComponent(trade.exchange)}&symbol=${encodeURIComponent(trade.symbol)}&market=${trade.market}&from=${bounds.from}&to=${bounds.to}&interval=${interval}`).then(v=>{if(active){setCandles(v.candles);setError('')}}).catch(e=>{if(active){setCandles([]);setError((e as Error).message)}}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[trade,bounds,interval]);
  const clampCenter=(zoom:number,center:number)=>Math.max(.5/zoom,Math.min(1-.5/zoom,center));
  const chart=useMemo(()=>{const W=1000,H=430,L=62,R=76,T=26,B=48,prices=candles.flatMap(v=>[v.high,v.low]);if(trade.entryPrice)prices.push(trade.entryPrice);if(trade.exitPrice)prices.push(trade.exitPrice);const min=Math.min(...prices),max=Math.max(...prices),pad=(max-min||Math.abs(max)*.01||1)*.12,fullLow=min-pad,fullHigh=max+pad,fullStart=candles[0]?.time||bounds.from,fullEnd=candles.at(-1)?.time||bounds.to,xHalf=.5/view.xz,yHalf=.5/view.yz,xc=clampCenter(view.xz,view.xc),yc=clampCenter(view.yz,view.yc),start=fullStart+(xc-xHalf)*(fullEnd-fullStart),end=fullStart+(xc+xHalf)*(fullEnd-fullStart),low=fullLow+(yc-yHalf)*(fullHigh-fullLow),high=fullLow+(yc+yHalf)*(fullHigh-fullLow),x=(v:number)=>L+(v-start)/(end-start||1)*(W-L-R),y=(v:number)=>T+(high-v)/(high-low)*(H-T-B),visible=candles.filter(v=>v.time>=start-interval&&v.time<=end+interval);return {W,H,L,R,T,B,low,high,start,end,x,y,visible};},[candles,trade,bounds,view,interval]);
  const point=(event:{clientX:number;clientY:number;currentTarget:SVGSVGElement})=>{const rect=event.currentTarget.getBoundingClientRect();return {x:(event.clientX-rect.left)/rect.width*chart.W,y:(event.clientY-rect.top)/rect.height*chart.H};};
  const zoom=(axis:'x'|'y',factor:number,anchor=.5)=>setView(old=>{if(axis==='x'){const next=Math.max(1,Math.min(100,old.xz*factor)),anchored=old.xc-.5/old.xz+anchor/old.xz;return {...old,xz:next,xc:clampCenter(next,anchored+(.5-anchor)/next)};}const next=Math.max(1,Math.min(100,old.yz*factor)),anchored=old.yc-.5/old.yz+anchor/old.yz;return {...old,yz:next,yc:clampCenter(next,anchored+(.5-anchor)/next)};});
  const wheel=(event:ReactWheelEvent<SVGSVGElement>)=>{event.preventDefault();const p=point(event),axis=event.shiftKey||p.x>chart.W-chart.R?'y':'x',anchor=axis==='x'?Math.max(0,Math.min(1,(p.x-chart.L)/(chart.W-chart.L-chart.R))):Math.max(0,Math.min(1,1-(p.y-chart.T)/(chart.H-chart.T-chart.B)));zoom(axis,event.deltaY<0?1.35:1/1.35,anchor);};
  const pointerDown=(event:ReactPointerEvent<SVGSVGElement>)=>{const p=point(event);if(p.x<chart.L||p.x>chart.W-chart.R||p.y<chart.T||p.y>chart.H-chart.B)return;event.currentTarget.setPointerCapture(event.pointerId);drag.current={x:p.x,y:p.y,view};};
  const pointerMove=(event:ReactPointerEvent<SVGSVGElement>)=>{if(!drag.current)return;const p=point(event),origin=drag.current;setView({...origin.view,xc:clampCenter(origin.view.xz,origin.view.xc-(p.x-origin.x)/(chart.W-chart.L-chart.R)/origin.view.xz),yc:clampCenter(origin.view.yz,origin.view.yc+(p.y-origin.y)/(chart.H-chart.T-chart.B)/origin.view.yz)});};
  const pointerUp=(event:ReactPointerEvent<SVGSVGElement>)=>{if(event.currentTarget.hasPointerCapture(event.pointerId))event.currentTarget.releasePointerCapture(event.pointerId);drag.current=null;};
  const marker=(execution:Execution,kind:'entry'|'exit',i:number)=>{const isEntry=kind==='entry',positive=trade.direction==='long'?isEntry:!isEntry,color=positive?'#20d67b':'#ff4d62',x=chart.x(execution.time),y=chart.y(execution.price),points=positive?`${x},${y-10} ${x-7},${y+2} ${x+7},${y+2}`:`${x},${y+10} ${x-7},${y-2} ${x+7},${y-2}`;return <polygon key={`${kind}-${execution.id}-${i}`} points={points} fill={color} stroke="#0e1421" strokeWidth="2"/>};
  return <section className="trade-chart-card"><div className="trade-chart-toolbar"><div><strong>{trade.direction==='long'?'LONG':trade.direction==='short'?'SHORT':'СДЕЛКА'} {trade.symbol}</strong><span>{trade.exchange} · UTC · потяните график для перемещения</span></div><div className="trade-chart-actions"><div className="chart-intervals">{intervals.map(([label,value])=><button key={value} className={interval===value?'active':''} onClick={()=>{setView(initialView);if(interval!==value){setLoading(true);setIntervalValue(value)}}}>{label}</button>)}</div><div className="chart-navigation" aria-label="Масштаб графика"><button onClick={()=>zoom('x',1/1.5)} aria-label="Отдалить по горизонтали">X−</button><button onClick={()=>zoom('x',1.5)} aria-label="Приблизить по горизонтали">X+</button><button onClick={()=>zoom('y',1/1.5)} aria-label="Отдалить по вертикали">Y−</button><button onClick={()=>zoom('y',1.5)} aria-label="Приблизить по вертикали">Y+</button><button onClick={()=>setView(initialView)}>Сброс</button></div></div></div>
    <div className="trade-chart-wrap">{loading&&<div className="chart-message">Загружаю историю рынка…</div>}{!loading&&!candles.length&&<div className="chart-message"><ChartCandlestick size={28}/><strong>Данные графика пока недоступны</strong><span>{error||'Биржа не вернула свечи за выбранный период. Исполнения сделки показаны ниже.'}</span></div>}
      {!!candles.length&&<svg className="interactive-trade-chart" viewBox={`0 0 ${chart.W} ${chart.H}`} role="img" aria-label={`Интерактивный график ${trade.symbol}`} onWheel={wheel} onPointerDown={pointerDown} onPointerMove={pointerMove} onPointerUp={pointerUp} onPointerCancel={pointerUp} onDoubleClick={()=>setView(initialView)}>
        <defs><clipPath id="trade-chart-plot"><rect x={chart.L} y={chart.T} width={chart.W-chart.L-chart.R} height={chart.H-chart.T-chart.B}/></clipPath></defs><rect width={chart.W} height={chart.H} fill="#0d1525"/>{[0,1,2,3,4].map(i=>{const yy=chart.T+i*(chart.H-chart.T-chart.B)/4,value=chart.high-i*(chart.high-chart.low)/4;return <g key={i}><line x1={chart.L} y1={yy} x2={chart.W-chart.R} y2={yy} stroke="#29354a" strokeDasharray="3 5"/><text x={chart.W-chart.R+9} y={yy+4} fill="#6ed9c2" fontSize="12">{value.toPrecision(6)}</text></g>})}
        <g clipPath="url(#trade-chart-plot)">{chart.visible.map(c=>{const xx=chart.x(c.time),up=c.close>=c.open,color=up?'#14d7b0':'#ff4868',body=Math.max(1,Math.abs(chart.y(c.open)-chart.y(c.close))),top=Math.min(chart.y(c.open),chart.y(c.close)),width=Math.max(1,760/Math.max(1,chart.visible.length));return <g key={c.time}><line x1={xx} y1={chart.y(c.high)} x2={xx} y2={chart.y(c.low)} stroke={color}/><rect x={xx-width/2} y={top} width={width} height={body} fill={color}/></g>})}
        {trade.entryPrice>0&&<g><line x1={chart.x(trade.entryTime)} y1={chart.y(trade.entryPrice)} x2={chart.W-chart.R} y2={chart.y(trade.entryPrice)} stroke={trade.direction==='short'?'#ff4d62':'#20d67b'} strokeDasharray="6 5"/><text x={chart.W-chart.R-5} y={chart.y(trade.entryPrice)-7} textAnchor="end" fill={trade.direction==='short'?'#ff6a79':'#45e795'} fontSize="12">Вход {trade.entryPrice}</text></g>}
        {trade.exitPrice>0&&<g><line x1={chart.x(trade.exitTime||trade.entryTime)} y1={chart.y(trade.exitPrice)} x2={chart.W-chart.R} y2={chart.y(trade.exitPrice)} stroke={trade.direction==='short'?'#20d67b':'#ff4d62'} strokeDasharray="6 5"/><text x={chart.W-chart.R-5} y={chart.y(trade.exitPrice)-7} textAnchor="end" fill={trade.direction==='short'?'#45e795':'#ff6a79'} fontSize="12">Выход {trade.exitPrice}</text></g>}
        {(trade.entries||[]).map((v,i)=>marker(v,'entry',i))}{(trade.exits||[]).map((v,i)=>marker(v,'exit',i))}</g>
        {chart.visible.filter((_,i)=>i%Math.max(1,Math.ceil(chart.visible.length/7))===0).map(c=>{const axis=interval===86400000?new Date(c.time).toLocaleDateString('ru-RU',{day:'2-digit',month:'2-digit',timeZone:'UTC'}):time(c.time).slice(0,5);return <text key={`axis-${c.time}`} x={chart.x(c.time)} y={chart.H-18} textAnchor="middle" fill="#55cdb9" fontSize="11">{axis}</text>})}
      </svg>}
    </div>
    <div className="execution-strip">{trade.executions.length?trade.executions.map((v,i)=><div key={`${v.id}-${i}`}><span className={v.side==='BUY'?'buy':'sell'}>{v.side==='BUY'?'BUY':'SELL'}</span><strong>{v.quantity} × {v.price}</strong><small><Clock3 size={12}/>{time(v.time)} UTC</small></div>):<p>Биржа сохранила PnL, но не вернула цены исполнений для этой записи.</p>}</div>
  </section>;
}

export function TradeExplorer({date,ticker,exchange,onBack}:{date:string;ticker:string;exchange:string;onBack:()=>void}){
  const [trades,setTrades]=useState<Trade[]>([]),[selected,setSelected]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState(''),[limited,setLimited]=useState(false);
  useEffect(()=>{let active=true;journalApi<{trades:Trade[];limited:boolean}>(`/trade-details?date=${date}&ticker=${encodeURIComponent(ticker)}&exchange=${encodeURIComponent(exchange)}`).then(v=>{if(active){setTrades(v.trades);setLimited(v.limited);setSelected(0);setError('')}}).catch(e=>{if(active)setError((e as Error).message)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[date,ticker,exchange]);
  const trade=trades[selected];return <div className="trade-explorer"><div className="trade-explorer-head"><button onClick={onBack}><ArrowLeft size={17}/>К разбивке</button><div><span>РАЗБОР СДЕЛОК · {date.split('-').reverse().join('.')}</span><h2>{ticker} <small>{exchange==='all'?'Все биржи':exchange}</small></h2></div><DialogClose className="icon-button trade-explorer-close" aria-label="Закрыть"><X size={20}/></DialogClose></div>
    {loading?<div className="empty-state">Загружаю исполнения…</div>:error?<div className="empty-state negative">{error}</div>:!trades.length?<div className="empty-state"><h3>Исполнения не найдены</h3><p>Запустите синхронизацию подключения. Новая версия загрузит цены и направления сделок.</p></div>:<><div className="trade-picker">{trades.map((v,i)=><button key={v.id} className={i===selected?'active':''} onClick={()=>setSelected(i)}><span>Сделка {i+1}<small>{v.exchange} · {time(v.exitTime||v.entryTime)} UTC</small></span><strong className={v.pnl-v.fee>=0?'positive':'negative'}>{money(v.pnl-v.fee)}</strong><em>{v.direction==='long'?'LONG':v.direction==='short'?'SHORT':'PNL'}</em></button>)}</div>{limited&&<p className="trade-data-note">Для старых записей доступны PnL и время. После синхронизации появятся цены входа, выхода и график.</p>}{trade&&<TradeChart key={trade.id} trade={trade}/>}</>}
  </div>;
}
