"use client";
import { useCallback,useEffect,useState } from 'react';
import { Check,ImagePlus,Pencil,Save,Trash2 } from 'lucide-react';
import Image from 'next/image';
import { journalApi } from './journal-server';

type NoteImage={id:string;name:string;mime:string;size:number;created:number};
const imageTypes=['image/png','image/jpeg','image/webp'],maxImages=10;
const fileBase64=(file:File)=>new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]||'');reader.onerror=()=>reject(new Error('Не удалось прочитать изображение.'));reader.readAsDataURL(file)});
const pastedImages=(data:DataTransfer)=>{const items=Array.from(data.items).filter(v=>v.kind==='file'&&v.type.startsWith('image/')).map(v=>v.getAsFile()).filter((v):v is File=>!!v);return items.length?items:Array.from(data.files).filter(v=>v.type.startsWith('image/'))};
function LinkedText({text}:{text:string}){return <div className="trade-note-text">{text.split(/(https?:\/\/[^\s]+)/g).map((part,i)=>/^https?:\/\//.test(part)?<a key={i} href={part} target="_blank" rel="noreferrer">{part}</a>:<span key={i}>{part}</span>)}</div>}

export function TradeNote({tradeKey}:{tradeKey:string}){
  const key=encodeURIComponent(tradeKey),[note,setNote]=useState(''),[draft,setDraft]=useState(''),[images,setImages]=useState<NoteImage[]>([]),[editing,setEditing]=useState(false),[busy,setBusy]=useState(true),[status,setStatus]=useState(''),[error,setError]=useState('');
  useEffect(()=>{let active=true;journalApi<{note:string;images:NoteImage[]}>(`/trade-notes/${key}`).then(v=>{if(active){setNote(v.note);setDraft(v.note);setImages(v.images);setEditing(!v.note&&!v.images.length)}}).catch(e=>{if(active)setError((e as Error).message)}).finally(()=>{if(active)setBusy(false)});return()=>{active=false}},[key]);
  async function save(){setBusy(true);setError('');setStatus('');try{await journalApi(`/trade-notes/${key}`,{note:draft});setNote(draft);setEditing(false);setStatus('Сохранено')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  const upload=useCallback(async(files:File[])=>{if(!files.length||busy)return;const available=maxImages-images.length;if(available<=0){setError('Для одной сделки можно сохранить не больше 10 скриншотов.');return}if(files.length>available){setError(`Можно добавить ещё ${available}.`);return}setBusy(true);setError('');setStatus('');try{const added:NoteImage[]=[];for(const file of files){if(!imageTypes.includes(file.type))throw new Error('Поддерживаются PNG, JPEG и WebP.');if(file.size>5*1024*1024)throw new Error('Размер одного изображения не должен превышать 5 МБ.');added.push(await journalApi<NoteImage>(`/trade-notes/${key}/images`,{name:file.name||'Скриншот',mime:file.type,data:await fileBase64(file)}))}setImages(v=>[...v,...added]);setStatus(added.length===1?'Скриншот добавлен':`Добавлено: ${added.length}`)}catch(e){setError((e as Error).message)}finally{setBusy(false)}},[busy,images.length,key]);
  async function remove(id:string){setBusy(true);setError('');try{await journalApi(`/trade-notes/${key}/images/${id}/delete`,{});setImages(v=>v.filter(image=>image.id!==id));setStatus('Изображение удалено')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  return <section className="trade-note" onPaste={event=>{const files=pastedImages(event.clipboardData);if(files.length){event.preventDefault();void upload(files)}}}>
    <div className="trade-note-head"><div><strong>Заметки к сделке</strong><span>Текст, скриншот или ссылка на YouTube</span></div>{!editing&&<button onClick={()=>setEditing(true)} aria-label="Изменить заметку"><Pencil size={14}/></button>}</div>
    {editing?<><textarea value={draft} maxLength={20000} autoFocus placeholder="Что планировал? Что сделал иначе? Вставьте текст, ссылку или скриншот…" onChange={e=>setDraft(e.target.value)}/><div className="trade-note-editor-foot"><span>{draft.length.toLocaleString('ru-RU')} / 20 000</span><button disabled={busy} onClick={()=>void save()}><Save size={14}/>{busy?'Сохранение…':'Сохранить'}</button></div></>:note?<LinkedText text={note}/>:<button className="trade-note-empty" onClick={()=>setEditing(true)}>Добавить заметку</button>}
    {!!images.length&&<div className="trade-note-gallery">{images.map(image=><figure key={image.id}><a href={`/api/journal/trade-notes/${key}/images/${image.id}`} target="_blank" rel="noreferrer"><Image unoptimized width={58} height={48} src={`/api/journal/trade-notes/${key}/images/${image.id}`} alt={image.name}/></a><button onClick={()=>void remove(image.id)} disabled={busy} aria-label={`Удалить ${image.name}`}><Trash2 size={13}/></button></figure>)}</div>}
    <div className="trade-note-tools"><label className={busy||images.length>=maxImages?'disabled':''}><ImagePlus size={14}/>Скриншот<input type="file" accept="image/png,image/jpeg,image/webp" multiple disabled={busy||images.length>=maxImages} onChange={e=>{void upload(Array.from(e.target.files||[]));e.currentTarget.value=''}}/></label><span>Ctrl+V · до 5 МБ · {images.length}/{maxImages}</span>{status&&<em><Check size={12}/>{status}</em>}</div>{error&&<p role="alert" className="server-error">{error}</p>}
  </section>
}
