import { createHash,createHmac } from 'node:crypto';
import { Wallet } from 'ethers';
import { decimal,units } from './security.mjs';
const DAY=86400000,hmac=(algo,key,text,enc='hex')=>createHmac(algo,key).update(text).digest(enc);
class ExchangeError extends Error{constructor(message,retryable=false,details={}){super(message);this.name='ExchangeError';this.retryable=retryable;Object.assign(this,details);}}
const safeAmount=v=>{try{return decimal(units(v||'0'));}catch{return '0';}};
const event=(v,x={})=>({id:String(x.id??v.id??v.tradeId??v.billId??v.orderId),time:Number(x.time??v.time??v.cTime??v.createdAt??v.ts),kind:x.kind||'fill',market:x.market||'futures',symbol:x.symbol??v.symbol??v.contract??v.instId??'',currency:x.currency??v.currency??v.marginCoin??v.feeCoin??v.feeCurrency??v.commissionAsset??'USDT',gross:safeAmount(x.gross),fee:safeAmount(x.fee),funding:safeAmount(x.funding),raw:v});
const stableTotal=rows=>decimal((rows||[]).reduce((n,v)=>{if(!['USDT','USDC','USD','FDUSD'].includes(v.asset||v.coin||v.currency))return n;const amount=v.equity??v.balance??(v.free!==undefined?decimal(units(v.free||'0')+units(v.locked||'0')):v.available||'0');return n+units(amount);},0n));
const kucoinError=error=>{const hints={400003:'API Key не существует либо создан для другого региона KuCoin',400004:'неверная API Passphrase',400005:'неверный API Secret или подпись',400006:'IP сервера не добавлен в whitelist ключа',400007:'ключу не выдано разрешение General',400008:'этот endpoint требует новый API-ключ v3',400009:'KuCoin отклонил версию API-ключа'};const hint=hints[String(error.code)];return hint?new ExchangeError(`KuCoin: ${hint} (код ${error.code}).`,error.retryable,{status:error.status,code:error.code}):error;};

async function parse(response){let text='',body;try{text=await response.text();body=JSON.parse(text);}catch{}const retryable=response.status===429||response.status===418||response.status>=500;if(!response.ok){const code=body?.code??body?.retCode,detail=body?.msg??body?.message??body?.retMsg;if(retryable)throw new ExchangeError(`Биржа временно ограничила запросы (HTTP ${response.status})${detail?`: ${detail}`:'.'}`,true,{status:response.status,code});throw new ExchangeError(`Биржа отклонила запрос (HTTP ${response.status}${code!==undefined?`, код ${code}`:''})${detail?`: ${detail}`:'. Проверьте ключ, passphrase, версию ключа, регион и IP.'}`,false,{status:response.status,code});}if(body===undefined)throw new ExchangeError('Некорректный ответ биржи.',true,{status:response.status});return body;}
async function send(fetchImpl,url,headers={}){let r;try{r=await fetchImpl(url,{method:'GET',headers,redirect:'error',signal:AbortSignal.timeout(20000)});}catch{throw new ExchangeError('Биржа недоступна или истекло время ожидания.',true);}return parse(r);}

export function createExtraAdapter(exchange,credentials,options={},fetchImpl=fetch){
  let lastAsterNonce=0n;
  let kucoinApiVersion=credentials.apiVersion?String(credentials.apiVersion):null;
  async function asterRpc(method,params){let response;try{response=await fetchImpl('https://tapi.asterdex.com/info',{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:1,method,params}),redirect:'error',signal:AbortSignal.timeout(20000)});}catch{throw new ExchangeError('Aster Chain RPC недоступен или истекло время ожидания.',true);}const body=await parse(response);if(body.error)throw new ExchangeError(`Aster RPC: ${body.error.message||body.error.code||'ошибка запроса'}`);return body.result;}
  async function mexcContract(path,params={}){const sorted=Object.entries(params).filter(([,v])=>v!==undefined).sort(([a],[b])=>a.localeCompare(b)),query=new URLSearchParams(sorted.map(([k,v])=>[k,String(v)])).toString(),ts=String(Date.now()),headers={'ApiKey':credentials.apiKey,'Request-Time':ts,'Signature':hmac('sha256',credentials.secret,credentials.apiKey+ts+query),'Content-Type':'application/json'},body=await send(fetchImpl,`https://api.mexc.com${path}${query?'?'+query:''}`,headers);if(body.success===false||Number(body.code)!==0)throw new ExchangeError(body.message||`Ошибка MEXC Futures ${body.code}.`);return body.data;}
  async function request(path,params={},host){
    const entries=Object.entries(params).filter(([,v])=>v!==undefined).map(([k,v])=>[k,String(v)]),query=new URLSearchParams(entries).toString(),now=Date.now();let url,headers={};
    if(exchange==='MEXC'){
      const signed=query+(query?'&':'')+`timestamp=${now}&recvWindow=10000`,base=host||'https://api.mexc.com';
      url=`${base}${path}?${signed}&signature=${hmac('sha256',credentials.secret,signed)}`;headers={'X-MBX-APIKEY':credentials.apiKey};
    }else if(exchange==='Gate.io'){
      const prefix='/api/v4',ts=String(Math.floor(now/1000)),rawQuery=entries.map(([k,v])=>`${k}=${v}`).join('&'),bodyHash=createHash('sha512').update('').digest('hex'),sign=`GET\n${prefix+path}\n${rawQuery}\n${bodyHash}\n${ts}`;
      url=`https://api.gateio.ws${prefix}${path}${query?'?'+query:''}`;headers={KEY:credentials.apiKey,Timestamp:ts,SIGN:hmac('sha512',credentials.secret,sign),Accept:'application/json','Content-Type':'application/json'};
    }else if(exchange==='Bitget'){
      const target=path+(query?'?'+query:''),ts=String(now);url='https://api.bitget.com'+target;headers={'ACCESS-KEY':credentials.apiKey,'ACCESS-TIMESTAMP':ts,'ACCESS-PASSPHRASE':credentials.passphrase,'ACCESS-SIGN':hmac('sha256',credentials.secret,ts+'GET'+target,'base64'),'Content-Type':'application/json','locale':'en-US'};
    }else if(exchange==='KuCoin'){
      const target=path+(query?'?'+query:''),base=host||'https://api.kucoin.com',versions=kucoinApiVersion?[kucoinApiVersion]:['3','2'];
      let lastError;
      for(const version of versions){const ts=String(Date.now());url=base+target;headers={'KC-API-KEY':credentials.apiKey,'KC-API-TIMESTAMP':ts,'KC-API-SIGN':hmac('sha256',credentials.secret,ts+'GET'+target,'base64'),'KC-API-PASSPHRASE':hmac('sha256',credentials.secret,credentials.passphrase,'base64'),'KC-API-KEY-VERSION':version,'Content-Type':'application/json','Accept':'application/json'};try{const body=await send(fetchImpl,url,headers);if(body.code!=='200000')throw new ExchangeError(`KuCoin отклонил запрос${body.code?` (код ${body.code})`:''}${body.msg?`: ${body.msg}`:'.'}`,false,{code:body.code});kucoinApiVersion=version;return body.data;}catch(error){lastError=error;if(kucoinApiVersion||!['400004','400005','400009'].includes(String(error.code)))throw kucoinError(error);}}
      throw kucoinError(lastError);
    }else if(exchange==='Lighter'){
      url=`https://mainnet.zklighter.elliot.ai${path}${query?'?'+query:''}`;
    }else throw new ExchangeError('Биржа пока не поддерживается.');
    const body=await send(fetchImpl,url,headers);
    if(exchange==='Bitget'&&body.code!=='00000')throw new ExchangeError(body.msg||`Ошибка Bitget API (${body.code}).`,false,{code:body.code});
    if(body?.code!==undefined&&Number(body.code)<0)throw new ExchangeError(body.msg||`Ошибка биржи ${body.code}.`);
    return exchange==='Bitget'?body.data:body;
  }
  async function asterPrivate(path,params={},host='https://fapi.asterdex.com'){
    const raw=String(credentials.secret||''),privateKey=raw.startsWith('0x')?raw:`0x${raw}`;let wallet;
    try{wallet=new Wallet(privateKey);}catch{throw new ExchangeError('Некорректный приватный ключ API Wallet Aster. Создайте новый read-only API Wallet.');}
    if(wallet.address.toLowerCase()!==String(credentials.apiKey||'').toLowerCase())throw new ExchangeError('Адрес API Wallet не соответствует приватному ключу. Скопируйте оба значения из одного read-only ключа Aster.');
    const next=BigInt(Date.now())*1000n;lastAsterNonce=next>lastAsterNonce?next:lastAsterNonce+1n;
    const signedParams={...params,nonce:lastAsterNonce.toString(),signer:wallet.address};
    const query=new URLSearchParams(Object.entries(signedParams).filter(([,v])=>v!==undefined).map(([k,v])=>[k,String(v)])).toString();
    const signature=await wallet.signTypedData({name:'AsterSignTransaction',version:'1',chainId:1666,verifyingContract:'0x0000000000000000000000000000000000000000'},{Message:[{name:'msg',type:'string'}]},{msg:query});
    let response;try{response=await fetchImpl(`${host}${path}?${query}&signature=${encodeURIComponent(signature)}`,{method:'GET',headers:{Accept:'application/json'},redirect:'error',signal:AbortSignal.timeout(20000)});}catch{throw new ExchangeError('Aster недоступен или истекло время ожидания.',true);}
    let body;try{body=JSON.parse(await response.text());}catch{throw new ExchangeError(`Aster вернул некорректный ответ (HTTP ${response.status}).`,response.status>=500);}
    if(!response.ok||body?.code!==undefined&&Number(body.code)!==0){const detail=typeof body?.msg==='string'?body.msg:typeof body?.message==='string'?body.message:'';throw new ExchangeError(`Aster отклонил запрос${body?.code!==undefined?` (${body.code})`:''}${detail?`: ${detail}`:` (HTTP ${response.status})`}.`,response.status===429||response.status>=500);}
    return body?.data??body;
  }
  async function verify(){
    if(exchange==='Aster'){if(!credentials.apiKey||!credentials.secret)throw new ExchangeError('Укажите адрес и приватный ключ read-only API Wallet Aster.');await asterPrivate('/fapi/v3/account');return;}
    if(exchange==='MEXC'){await request('/api/v3/account');if(options.futures!==false)await mexcContract('/api/v1/private/account/assets');return;}
    if(exchange==='Gate.io')return void await request('/spot/accounts');
    if(exchange==='Bitget'){try{await request('/api/v2/spot/account/assets');options.accountMode='classic';return;}catch(error){if(String(error.code)!=='40085')throw error;}const info=await request('/api/v3/account/info'),permType=String(info.permType||'').toLowerCase().replace(/[^a-z]/g,'');if(['readandwrite','readwrite','write','trade'].includes(permType))throw new ExchangeError('Ключ Bitget имеет право записи. Создайте отдельный ключ только для чтения.');const permissions=(Array.isArray(info.permissions)?info.permissions:[]).map(v=>String(v).toLowerCase());if(permissions.includes('withdraw'))throw new ExchangeError('Отключите у ключа Bitget разрешение Withdraw.');if(!permissions.includes('uta_mgt')||!permissions.includes('uta_trade'))throw new ExchangeError('Для Bitget UTA включите у read-only ключа разрешения UTA management и UTA trading.');await request('/api/v3/account/assets');options.accountMode='uta';return;}
    if(exchange==='KuCoin'){const info=await request('/api/v1/user/api-key');if(String(info.permission||'').split(',').some(v=>['Withdrawal','Transfer','InnerTransfer','FlexTransfers'].includes(v)))throw new ExchangeError('Отключите у ключа KuCoin вывод и переводы. Оставьте General для чтения.');return;}
    const accounts=await request('/api/v1/account',{by:'l1_address',value:credentials.address,active_only:false});if(!(accounts.accounts||accounts.data||[]).length)throw new ExchangeError('Аккаунт Lighter по этому адресу не найден.');
  }
  async function prepare(){
    if(exchange!=='MEXC'||options.spotAuto===false||options.mexcDiscoveryAt&&Date.now()-options.mexcDiscoveryAt<7*DAY)return false;
    const configured=(options.spotSymbols||[]).map(v=>String(v).toUpperCase()),self=await request('/api/v3/selfSymbols'),listed=Array.isArray(self?.data)?self.data:Array.isArray(self)?self:[];
    options.mexcSpotSymbols=[...new Set([...configured,...listed].map(v=>String(v).toUpperCase()).filter(v=>/^[A-Z0-9]{4,30}$/.test(v)))].sort();
    if(options.futures!==false){
      const futures=new Set((options.mexcFuturesSymbols||configured.map(v=>v.replace(/(USDT|USDC)$/,'_$1'))).filter(v=>/^[A-Z0-9]+_(USDT|USDC)$/.test(v)));
      for(let page=1;page<=100;page++){
        const data=await mexcContract('/api/v1/private/position/list/history_positions',{page_num:page,page_size:100}),rows=data?.resultList||data||[];
        for(const row of rows)if(/^[A-Z0-9]+_(USDT|USDC)$/.test(String(row.symbol||'')))futures.add(String(row.symbol));
        const total=Number(data?.totalPage||0);if(!Array.isArray(rows)||rows.length<100||total&&page>=total)break;
      }
      options.mexcFuturesSymbols=[...futures].sort();
    }else options.mexcFuturesSymbols=[];
    options.mexcDiscoveryAt=Date.now();return true;
  }
  async function snapshot(){
    if(exchange==='Aster'){if(!credentials.apiKey||!credentials.secret)throw new ExchangeError('Переподключите Aster с read-only API Wallet.');const [futures,spot]=await Promise.all([asterPrivate('/fapi/v3/account'),asterPrivate('/api/v3/account',{},'https://sapi.asterdex.com').catch(()=>null)]);const futuresEquity=Array.isArray(futures)?stableTotal(futures):futures.totalMarginBalance||futures.totalWalletBalance||stableTotal(futures.assets||futures.balances||[]);return {equityUsd:decimal(units(futuresEquity||'0')+units(stableTotal(spot?.balances||[]))),availableUsd:Array.isArray(futures)?null:futures.availableBalance||null,wallet:futures,spot,scope:'spot-stablecoins+perpetuals'};}
    if(exchange==='MEXC'){const a=await request('/api/v3/account'),f=options.futures!==false?await mexcContract('/api/v1/private/account/assets'):[];return {equityUsd:decimal(units(stableTotal(a.balances))+units(stableTotal(f))),spot:a,futures:f,scope:'spot-stablecoins+futures',warning:'В spot-капитале учитываются USD-стейблкоины; остальные spot-активы пока не оценены.'};}
    if(exchange==='Gate.io'){const [spot,futures]=await Promise.all([request('/spot/accounts'),request('/futures/usdt/accounts')]);return {equityUsd:decimal(units(stableTotal(spot))+units(futures.total||futures.total_equity||'0')),spot,futures,scope:'spot-stablecoins+usdt-futures'};}
    if(exchange==='Bitget'){if(options.accountMode==='uta'){const [account,funding]=await Promise.all([request('/api/v3/account/assets'),request('/api/v3/account/funding-assets')]);return {equityUsd:decimal(units(account.accountEquity||account.usdtEquity||'0')+units(stableTotal(funding))),account,funding,scope:'uta-equity+funding-stablecoins',warning:'UTA equity включает spot и derivatives. В Funding дополнительно учитываются USD-стейблкоины; прочие funding-активы пока не оценены.'};}const [spot,usdt,usdc]=await Promise.all([request('/api/v2/spot/account/assets'),request('/api/v2/mix/account/accounts',{productType:'USDT-FUTURES'}),request('/api/v2/mix/account/accounts',{productType:'USDC-FUTURES'})]);const fs=[...(usdt||[]),...(usdc||[])].reduce((n,v)=>n+units(v.accountEquity||v.usdtEquity||'0'),0n);return {equityUsd:decimal(units(stableTotal(spot))+fs),spot,futures:[...usdt,...usdc],scope:'spot-stablecoins+futures'};}
    if(exchange==='KuCoin'){const [spot,futures]=await Promise.all([request('/api/v1/accounts'),request('/api/v1/account-overview',{currency:'USDT'},'https://api-futures.kucoin.com')]);return {equityUsd:decimal(units(stableTotal(spot))+units(futures.accountEquity||'0')),spot,futures,scope:'spot-stablecoins+usdt-futures'};}
    const a=await request('/api/v1/account',{by:'l1_address',value:credentials.address,active_only:false}),account=(a.accounts||a.data||[])[0]||{};return {equityUsd:account.collateral||account.total_asset_value||account.available_balance||'0',wallet:account,scope:'lighter-account'};
  }
  function streams(now){
    if(exchange==='Aster')return [{id:'income',start:0,window:7*DAY}];
    if(exchange==='MEXC'){const spot=options.mexcSpotSymbols||options.spotSymbols||[],futures=options.mexcFuturesSymbols||(options.spotSymbols||[]).map(symbol=>symbol.replace(/(USDT|USDC)$/,'_$1'));return [...spot.map(symbol=>({id:'spot:'+symbol,start:now-30*DAY,window:7*DAY})),...(options.futures===false?[]:futures.map(symbol=>({id:'futures:'+symbol,start:now-89*DAY,window:89*DAY})))];}
    if(exchange==='Gate.io')return [{id:'spot',start:now-365*DAY,window:7*DAY},...['pnl','fee','fund'].map(type=>({id:`futures:${type}`,start:now-179*DAY,window:7*DAY}))];
    if(exchange==='Bitget'){if(options.accountMode==='uta'){const categories=['SPOT','MARGIN','USDT-FUTURES','USDC-FUTURES','COIN-FUTURES'];return [...categories.map(category=>({id:`uta-fills:${category}`,start:now-89*DAY,window:30*DAY})),...categories.slice(2).map(category=>({id:`uta-funding:${category}`,start:now-89*DAY,window:30*DAY}))];}return ['USDT-FUTURES','USDC-FUTURES'].map(id=>({id:'bills:'+id,start:now-89*DAY,window:7*DAY}));}
    if(exchange==='KuCoin')return [{id:'futures-ledger',start:now-365*DAY,window:DAY}];
    return [];
  }
  async function page(stream,start,end,cursor){let rows=[],next=null;
    if(exchange==='Aster'){if(!credentials.apiKey||!credentials.secret)throw new ExchangeError('Удалите это подключение и добавьте Aster заново с read-only API Wallet.');rows=await asterPrivate('/fapi/v3/income',{startTime:start,endTime:end,limit:1000});return {events:rows.map((v,i)=>event(v,{id:v.tranId||`${v.time}:${v.incomeType}:${v.symbol}:${i}`,time:v.time,kind:['REALIZED_PNL','COMMISSION','FUNDING_FEE'].includes(v.incomeType)?'pnl':'transfer',market:'futures',symbol:v.symbol,gross:v.incomeType==='REALIZED_PNL'?v.income:'0',fee:v.incomeType==='COMMISSION'?decimal(-units(v.income)):'0',funding:v.incomeType==='FUNDING_FEE'?v.income:'0',currency:v.asset||'USDT'})),next:null};}
    if(exchange==='MEXC'){const futures=stream.startsWith('futures:'),symbol=stream.slice(futures?8:5);if(futures){const r=await mexcContract('/api/v1/private/order/list/order_deals',{symbol,start_time:start,end_time:end,page_num:cursor||1,page_size:100});rows=r?.resultList||r||[];next=rows.length===100?String(Number(cursor||1)+1):null;return {events:rows.map(v=>event(v,{market:'futures',kind:'pnl',time:v.timestamp,symbol:v.symbol,gross:v.profit,fee:v.fee,currency:v.feeCurrency||'USDT'})),next};}rows=await request('/api/v3/myTrades',{symbol,startTime:start,endTime:end,limit:1000,fromId:cursor||undefined});next=rows.length===1000?String(rows.at(-1).id):null;return {events:rows.map(v=>event(v,{market:'spot',symbol,fee:v.commission,currency:v.commissionAsset,time:v.time})),next};}
    if(exchange==='Gate.io'){const spot=stream==='spot';rows=spot?await request('/spot/my_trades',{from:Math.floor(start/1000),to:Math.floor(end/1000),limit:1000,page:cursor||1}):await request('/futures/usdt/account_book',{from:Math.floor(start/1000),to:Math.floor(end/1000),limit:1000,type:stream.slice(8)});next=spot&&rows.length===1000?String(Number(cursor||1)+1):null;return {events:rows.map(v=>spot?event(v,{market:'spot',time:Number(v.create_time_ms||v.create_time*1000),symbol:v.currency_pair,fee:v.fee,currency:v.fee_currency}):event(v,{kind:'pnl',time:Number(v.time)*1000,symbol:v.contract,gross:v.type==='pnl'?v.change:'0',fee:v.type==='fee'?decimal(-units(v.change)):'0',funding:v.type==='fund'?v.change:'0',currency:'USDT'})),next};}
    if(exchange==='Bitget'){if(stream.startsWith('uta-')){const fills=stream.startsWith('uta-fills:'),category=stream.slice(fills?10:12),r=await request(fills?'/api/v3/trade/fills':'/api/v3/account/financial-records',{category,startTime:start,endTime:end,limit:100,cursor:cursor||undefined});rows=r?.list||[];next=r?.cursor||null;if(fills){const events=[];for(const v of rows){const detail=(v.feeDetail||[])[0]||{},fee=safeAmount(detail.fee),currency=detail.feeCoin||(category==='USDC-FUTURES'?'USDC':'USDT'),market=['SPOT','MARGIN'].includes(category)?'spot':'futures',raw={...v,fee};events.push(event(raw,{id:`fill:${v.execId}`,time:v.createdTime,kind:'fill',market,symbol:v.symbol,currency}));if(v.execPnl!=='0'||fee!=='0')events.push(event(raw,{id:`pnl:${v.execId}`,time:v.createdTime,kind:'pnl',market,symbol:v.symbol,gross:v.execPnl||'0',fee,currency}));}return {events,next};}const fundingTypes=new Set(['CONTRACT_MAIN_SETTLE_FEE_USER_IN','CONTRACT_MAIN_SETTLE_FEE_USER_OUT','MARGIN_SETTLE_FEE_USER_IN','MARGIN_SETTLE_FEE_USER_OUT']),events=rows.filter(v=>fundingTypes.has(String(v.type).toUpperCase())).map(v=>{const type=String(v.type).toUpperCase(),amount=units(v.amount||'0'),signed=type.endsWith('_OUT')&&amount>0n?-amount:amount;return event(v,{id:`funding:${v.id}`,time:v.ts,kind:'pnl',market:'futures',symbol:v.symbol,funding:decimal(signed),currency:v.coin||(category==='USDC-FUTURES'?'USDC':'USDT')});});return {events,next};}const productType=stream.slice(6),r=await request('/api/v2/mix/account/bill',{productType,startTime:start,endTime:end,limit:100,idLessThan:cursor||undefined});rows=r?.bills||r||[];next=rows.length===100?String(rows.at(-1).id||rows.at(-1).billId):null;return {events:rows.map(v=>event(v,{id:v.billId||v.id,time:v.cTime||v.ctime,kind:'pnl',symbol:v.symbol,gross:v.businessType==='close_position'?v.amount:'0',fee:String(v.businessType||'').includes('fee')?decimal(-units(v.amount)):'0',funding:String(v.businessType||'').includes('funding')?v.amount:'0',currency:v.marginCoin||'USDT'})),next};}
    if(exchange==='KuCoin'){const r=await request('/api/v1/transaction-history',{startAt:start,endAt:end,maxCount:50,offset:cursor||undefined,forward:true},'https://api-futures.kucoin.com');rows=r.dataList||[];next=r.hasMore&&rows.length?String(rows.at(-1).offset):null;return {events:rows.map(v=>event(v,{id:v.offset,time:v.time,kind:['RealisedPNL','FundingFee','TradingFee'].includes(v.type)?'pnl':'transfer',symbol:v.remark,gross:v.type==='RealisedPNL'?v.amount:'0',fee:v.type==='TradingFee'?decimal(-units(v.amount)):'0',funding:v.type==='FundingFee'?v.amount:'0',currency:v.currency})),next};}
    return {events:[],next:null};
  }
  return {verify,prepare,snapshot,streams,page};
}
